package com.ums.mbr.service.core.mapper;

import com.ums.mbr.service.domain.BizType;
import com.ums.mbr.service.core.example.BizTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_biz_type
     *
     * @mbg.generated
     */
    long countByExample(BizTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_biz_type
     *
     * @mbg.generated
     */
    int deleteByExample(BizTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_biz_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_biz_type
     *
     * @mbg.generated
     */
    int insert(BizType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_biz_type
     *
     * @mbg.generated
     */
    int insertSelective(BizType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_biz_type
     *
     * @mbg.generated
     */
    List<BizType> selectByExample(BizTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_biz_type
     *
     * @mbg.generated
     */
    BizType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_biz_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BizType record, @Param("example") BizTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_biz_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BizType record, @Param("example") BizTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_biz_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BizType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_biz_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BizType record);
}