package com.ums.mbr.service.core.mapper;

import com.ums.mbr.service.domain.Card;
import com.ums.mbr.service.core.example.CardExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    long countByExample(CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    int deleteByExample(CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String retserial);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    int insert(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    int insertSelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    List<Card> selectByExample(CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    Card selectByPrimaryKey(String retserial);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Card record, @Param("example") CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Card record, @Param("example") CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Card record);
}