package com.ums.mbr.service.core.mapper;

import com.ums.mbr.service.domain.Coupon;
import com.ums.mbr.service.core.example.CouponExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    long countByExample(CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String retserial);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    int insert(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    int insertSelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    List<Coupon> selectByExample(CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    Coupon selectByPrimaryKey(String retserial);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Coupon record, @Param("example") CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Coupon record, @Param("example") CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Coupon record);
}