package com.ums.mbr.service.core.mapper;

import com.ums.mbr.service.domain.HisTradeInf;
import com.ums.mbr.service.core.example.HisTradeInfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HisTradeInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histradeinf
     *
     * @mbg.generated
     */
    long countByExample(HisTradeInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histradeinf
     *
     * @mbg.generated
     */
    int deleteByExample(HisTradeInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histradeinf
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String retserial);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histradeinf
     *
     * @mbg.generated
     */
    int insert(HisTradeInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histradeinf
     *
     * @mbg.generated
     */
    int insertSelective(HisTradeInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histradeinf
     *
     * @mbg.generated
     */
    List<HisTradeInf> selectByExample(HisTradeInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histradeinf
     *
     * @mbg.generated
     */
    HisTradeInf selectByPrimaryKey(String retserial);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histradeinf
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HisTradeInf record, @Param("example") HisTradeInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histradeinf
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HisTradeInf record, @Param("example") HisTradeInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histradeinf
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HisTradeInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histradeinf
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HisTradeInf record);
}