package com.ums.mbr.service.core.mapper;

import com.ums.mbr.service.domain.HisTransLog;
import com.ums.mbr.service.core.example.HisTransLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HisTransLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histranslog
     *
     * @mbg.generated
     */
    long countByExample(HisTransLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histranslog
     *
     * @mbg.generated
     */
    int deleteByExample(HisTransLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histranslog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String retserial);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histranslog
     *
     * @mbg.generated
     */
    int insert(HisTransLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histranslog
     *
     * @mbg.generated
     */
    int insertSelective(HisTransLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histranslog
     *
     * @mbg.generated
     */
    List<HisTransLog> selectByExample(HisTransLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histranslog
     *
     * @mbg.generated
     */
    HisTransLog selectByPrimaryKey(String retserial);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histranslog
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HisTransLog record, @Param("example") HisTransLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histranslog
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HisTransLog record, @Param("example") HisTransLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histranslog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HisTransLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_histranslog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HisTransLog record);
}