package com.ums.mbr.service.core.mapper;

import com.ums.mbr.service.domain.Mcht;
import com.ums.mbr.service.core.example.MchtExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MchtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_mcht
     *
     * @mbg.generated
     */
    long countByExample(MchtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_mcht
     *
     * @mbg.generated
     */
    int deleteByExample(MchtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_mcht
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String mchtno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_mcht
     *
     * @mbg.generated
     */
    int insert(Mcht record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_mcht
     *
     * @mbg.generated
     */
    int insertSelective(Mcht record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_mcht
     *
     * @mbg.generated
     */
    List<Mcht> selectByExample(MchtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_mcht
     *
     * @mbg.generated
     */
    Mcht selectByPrimaryKey(String mchtno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_mcht
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Mcht record, @Param("example") MchtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_mcht
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Mcht record, @Param("example") MchtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_mcht
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Mcht record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_mcht
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Mcht record);
}