package com.ums.mbr.service.core.mapper;

import com.ums.mbr.service.domain.OrderInf;
import com.ums.mbr.service.core.example.OrderInfExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_orderinf
     *
     * @mbg.generated
     */
    long countByExample(OrderInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_orderinf
     *
     * @mbg.generated
     */
    int deleteByExample(OrderInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_orderinf
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String retserial);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_orderinf
     *
     * @mbg.generated
     */
    int insert(OrderInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_orderinf
     *
     * @mbg.generated
     */
    int insertSelective(OrderInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_orderinf
     *
     * @mbg.generated
     */
    List<OrderInf> selectByExample(OrderInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_orderinf
     *
     * @mbg.generated
     */
    OrderInf selectByPrimaryKey(String retserial);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_orderinf
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrderInf record, @Param("example") OrderInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_orderinf
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrderInf record, @Param("example") OrderInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_orderinf
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderInf record);

    int updateByOrderNoSelective(OrderInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_orderinf
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderInf record);
}