package com.ums.mbr.service.core.mapper;

import com.ums.mbr.service.domain.RootKey;
import com.ums.mbr.service.core.example.RootKeyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RootKeyMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_rootkey
     *
     * @mbg.generated
     */
    RootKey selectByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rootkey
     *
     * @mbg.generated
     */
    long countByExample(RootKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rootkey
     *
     * @mbg.generated
     */
    int deleteByExample(RootKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rootkey
     *
     * @mbg.generated
     */
    int insert(RootKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rootkey
     *
     * @mbg.generated
     */
    int insertSelective(RootKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rootkey
     *
     * @mbg.generated
     */
    List<RootKey> selectByExample(RootKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rootkey
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RootKey record, @Param("example") RootKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rootkey
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RootKey record, @Param("example") RootKeyExample example);
}