package com.ums.mbr.service.core.mapper;

import com.ums.mbr.service.domain.Term;
import com.ums.mbr.service.core.example.TermExample;
import com.ums.mbr.service.domain.TermKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    long countByExample(TermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    int deleteByExample(TermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TermKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    int insert(Term record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    int insertSelective(Term record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    List<Term> selectByExample(TermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    Term selectByPrimaryKey(TermKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Term record, @Param("example") TermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Term record, @Param("example") TermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Term record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Term record);
}