package com.ums.mbr.service.core.mapper;

import com.ums.mbr.service.domain.TradeInf;
import com.ums.mbr.service.core.example.TradeInfExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TradeInfMapper {
    int updateByTradeNoSelective(TradeInf record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_tradeinf
     *
     * @mbg.generated
     */
    long countByExample(TradeInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_tradeinf
     *
     * @mbg.generated
     */
    int deleteByExample(TradeInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_tradeinf
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String retserial);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_tradeinf
     *
     * @mbg.generated
     */
    int insert(TradeInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_tradeinf
     *
     * @mbg.generated
     */
    int insertSelective(TradeInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_tradeinf
     *
     * @mbg.generated
     */
    List<TradeInf> selectByExample(TradeInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_tradeinf
     *
     * @mbg.generated
     */
    TradeInf selectByPrimaryKey(String retserial);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_tradeinf
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TradeInf record, @Param("example") TradeInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_tradeinf
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TradeInf record, @Param("example") TradeInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_tradeinf
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TradeInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_tradeinf
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeInf record);
}