package com.ums.mbr.service.core.example;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class CategoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_category
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_category
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_category
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated
     */
    public CategoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_category
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFirstLevelIsNull() {
            addCriterion("FIRST_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andFirstLevelIsNotNull() {
            addCriterion("FIRST_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andFirstLevelEqualTo(String value) {
            addCriterion("FIRST_LEVEL =", value, "firstLevel");
            return (Criteria) this;
        }

        public Criteria andFirstLevelNotEqualTo(String value) {
            addCriterion("FIRST_LEVEL <>", value, "firstLevel");
            return (Criteria) this;
        }

        public Criteria andFirstLevelGreaterThan(String value) {
            addCriterion("FIRST_LEVEL >", value, "firstLevel");
            return (Criteria) this;
        }

        public Criteria andFirstLevelGreaterThanOrEqualTo(String value) {
            addCriterion("FIRST_LEVEL >=", value, "firstLevel");
            return (Criteria) this;
        }

        public Criteria andFirstLevelLessThan(String value) {
            addCriterion("FIRST_LEVEL <", value, "firstLevel");
            return (Criteria) this;
        }

        public Criteria andFirstLevelLessThanOrEqualTo(String value) {
            addCriterion("FIRST_LEVEL <=", value, "firstLevel");
            return (Criteria) this;
        }

        public Criteria andFirstLevelLike(String value) {
            addCriterion("FIRST_LEVEL like", value, "firstLevel");
            return (Criteria) this;
        }

        public Criteria andFirstLevelNotLike(String value) {
            addCriterion("FIRST_LEVEL not like", value, "firstLevel");
            return (Criteria) this;
        }

        public Criteria andFirstLevelIn(List<String> values) {
            addCriterion("FIRST_LEVEL in", values, "firstLevel");
            return (Criteria) this;
        }

        public Criteria andFirstLevelNotIn(List<String> values) {
            addCriterion("FIRST_LEVEL not in", values, "firstLevel");
            return (Criteria) this;
        }

        public Criteria andFirstLevelBetween(String value1, String value2) {
            addCriterion("FIRST_LEVEL between", value1, value2, "firstLevel");
            return (Criteria) this;
        }

        public Criteria andFirstLevelNotBetween(String value1, String value2) {
            addCriterion("FIRST_LEVEL not between", value1, value2, "firstLevel");
            return (Criteria) this;
        }

        public Criteria andSecondLevelIsNull() {
            addCriterion("SECOND_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andSecondLevelIsNotNull() {
            addCriterion("SECOND_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andSecondLevelEqualTo(String value) {
            addCriterion("SECOND_LEVEL =", value, "secondLevel");
            return (Criteria) this;
        }

        public Criteria andSecondLevelNotEqualTo(String value) {
            addCriterion("SECOND_LEVEL <>", value, "secondLevel");
            return (Criteria) this;
        }

        public Criteria andSecondLevelGreaterThan(String value) {
            addCriterion("SECOND_LEVEL >", value, "secondLevel");
            return (Criteria) this;
        }

        public Criteria andSecondLevelGreaterThanOrEqualTo(String value) {
            addCriterion("SECOND_LEVEL >=", value, "secondLevel");
            return (Criteria) this;
        }

        public Criteria andSecondLevelLessThan(String value) {
            addCriterion("SECOND_LEVEL <", value, "secondLevel");
            return (Criteria) this;
        }

        public Criteria andSecondLevelLessThanOrEqualTo(String value) {
            addCriterion("SECOND_LEVEL <=", value, "secondLevel");
            return (Criteria) this;
        }

        public Criteria andSecondLevelLike(String value) {
            addCriterion("SECOND_LEVEL like", value, "secondLevel");
            return (Criteria) this;
        }

        public Criteria andSecondLevelNotLike(String value) {
            addCriterion("SECOND_LEVEL not like", value, "secondLevel");
            return (Criteria) this;
        }

        public Criteria andSecondLevelIn(List<String> values) {
            addCriterion("SECOND_LEVEL in", values, "secondLevel");
            return (Criteria) this;
        }

        public Criteria andSecondLevelNotIn(List<String> values) {
            addCriterion("SECOND_LEVEL not in", values, "secondLevel");
            return (Criteria) this;
        }

        public Criteria andSecondLevelBetween(String value1, String value2) {
            addCriterion("SECOND_LEVEL between", value1, value2, "secondLevel");
            return (Criteria) this;
        }

        public Criteria andSecondLevelNotBetween(String value1, String value2) {
            addCriterion("SECOND_LEVEL not between", value1, value2, "secondLevel");
            return (Criteria) this;
        }

        public Criteria andThirdLevelIsNull() {
            addCriterion("THIRD_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andThirdLevelIsNotNull() {
            addCriterion("THIRD_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andThirdLevelEqualTo(String value) {
            addCriterion("THIRD_LEVEL =", value, "thirdLevel");
            return (Criteria) this;
        }

        public Criteria andThirdLevelNotEqualTo(String value) {
            addCriterion("THIRD_LEVEL <>", value, "thirdLevel");
            return (Criteria) this;
        }

        public Criteria andThirdLevelGreaterThan(String value) {
            addCriterion("THIRD_LEVEL >", value, "thirdLevel");
            return (Criteria) this;
        }

        public Criteria andThirdLevelGreaterThanOrEqualTo(String value) {
            addCriterion("THIRD_LEVEL >=", value, "thirdLevel");
            return (Criteria) this;
        }

        public Criteria andThirdLevelLessThan(String value) {
            addCriterion("THIRD_LEVEL <", value, "thirdLevel");
            return (Criteria) this;
        }

        public Criteria andThirdLevelLessThanOrEqualTo(String value) {
            addCriterion("THIRD_LEVEL <=", value, "thirdLevel");
            return (Criteria) this;
        }

        public Criteria andThirdLevelLike(String value) {
            addCriterion("THIRD_LEVEL like", value, "thirdLevel");
            return (Criteria) this;
        }

        public Criteria andThirdLevelNotLike(String value) {
            addCriterion("THIRD_LEVEL not like", value, "thirdLevel");
            return (Criteria) this;
        }

        public Criteria andThirdLevelIn(List<String> values) {
            addCriterion("THIRD_LEVEL in", values, "thirdLevel");
            return (Criteria) this;
        }

        public Criteria andThirdLevelNotIn(List<String> values) {
            addCriterion("THIRD_LEVEL not in", values, "thirdLevel");
            return (Criteria) this;
        }

        public Criteria andThirdLevelBetween(String value1, String value2) {
            addCriterion("THIRD_LEVEL between", value1, value2, "thirdLevel");
            return (Criteria) this;
        }

        public Criteria andThirdLevelNotBetween(String value1, String value2) {
            addCriterion("THIRD_LEVEL not between", value1, value2, "thirdLevel");
            return (Criteria) this;
        }

        public Criteria andRateIsNull() {
            addCriterion("RATE is null");
            return (Criteria) this;
        }

        public Criteria andRateIsNotNull() {
            addCriterion("RATE is not null");
            return (Criteria) this;
        }

        public Criteria andRateEqualTo(BigDecimal value) {
            addCriterion("RATE =", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotEqualTo(BigDecimal value) {
            addCriterion("RATE <>", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateGreaterThan(BigDecimal value) {
            addCriterion("RATE >", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RATE >=", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLessThan(BigDecimal value) {
            addCriterion("RATE <", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RATE <=", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateIn(List<BigDecimal> values) {
            addCriterion("RATE in", values, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotIn(List<BigDecimal> values) {
            addCriterion("RATE not in", values, "rate");
            return (Criteria) this;
        }

        public Criteria andRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RATE between", value1, value2, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RATE not between", value1, value2, "rate");
            return (Criteria) this;
        }

        public Criteria andSettIntervalIsNull() {
            addCriterion("SETT_INTERVAL is null");
            return (Criteria) this;
        }

        public Criteria andSettIntervalIsNotNull() {
            addCriterion("SETT_INTERVAL is not null");
            return (Criteria) this;
        }

        public Criteria andSettIntervalEqualTo(String value) {
            addCriterion("SETT_INTERVAL =", value, "settInterval");
            return (Criteria) this;
        }

        public Criteria andSettIntervalNotEqualTo(String value) {
            addCriterion("SETT_INTERVAL <>", value, "settInterval");
            return (Criteria) this;
        }

        public Criteria andSettIntervalGreaterThan(String value) {
            addCriterion("SETT_INTERVAL >", value, "settInterval");
            return (Criteria) this;
        }

        public Criteria andSettIntervalGreaterThanOrEqualTo(String value) {
            addCriterion("SETT_INTERVAL >=", value, "settInterval");
            return (Criteria) this;
        }

        public Criteria andSettIntervalLessThan(String value) {
            addCriterion("SETT_INTERVAL <", value, "settInterval");
            return (Criteria) this;
        }

        public Criteria andSettIntervalLessThanOrEqualTo(String value) {
            addCriterion("SETT_INTERVAL <=", value, "settInterval");
            return (Criteria) this;
        }

        public Criteria andSettIntervalLike(String value) {
            addCriterion("SETT_INTERVAL like", value, "settInterval");
            return (Criteria) this;
        }

        public Criteria andSettIntervalNotLike(String value) {
            addCriterion("SETT_INTERVAL not like", value, "settInterval");
            return (Criteria) this;
        }

        public Criteria andSettIntervalIn(List<String> values) {
            addCriterion("SETT_INTERVAL in", values, "settInterval");
            return (Criteria) this;
        }

        public Criteria andSettIntervalNotIn(List<String> values) {
            addCriterion("SETT_INTERVAL not in", values, "settInterval");
            return (Criteria) this;
        }

        public Criteria andSettIntervalBetween(String value1, String value2) {
            addCriterion("SETT_INTERVAL between", value1, value2, "settInterval");
            return (Criteria) this;
        }

        public Criteria andSettIntervalNotBetween(String value1, String value2) {
            addCriterion("SETT_INTERVAL not between", value1, value2, "settInterval");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("NOTE is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("NOTE is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("NOTE =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("NOTE <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("NOTE >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("NOTE >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("NOTE <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("NOTE <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("NOTE like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("NOTE not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("NOTE in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("NOTE not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("NOTE between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("NOTE not between", value1, value2, "note");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_category
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_category
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}