package com.ums.mbr.service.core.example;

import java.util.ArrayList;
import java.util.List;

public class ErrCodeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_err_code
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_err_code
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_err_code
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_err_code
     *
     * @mbg.generated
     */
    public ErrCodeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_err_code
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_err_code
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_err_code
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_err_code
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_err_code
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_err_code
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_err_code
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_err_code
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_err_code
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_err_code
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_err_code
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("CODE in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("CODE not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andMsgIsNull() {
            addCriterion("MSG is null");
            return (Criteria) this;
        }

        public Criteria andMsgIsNotNull() {
            addCriterion("MSG is not null");
            return (Criteria) this;
        }

        public Criteria andMsgEqualTo(String value) {
            addCriterion("MSG =", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotEqualTo(String value) {
            addCriterion("MSG <>", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgGreaterThan(String value) {
            addCriterion("MSG >", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgGreaterThanOrEqualTo(String value) {
            addCriterion("MSG >=", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLessThan(String value) {
            addCriterion("MSG <", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLessThanOrEqualTo(String value) {
            addCriterion("MSG <=", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLike(String value) {
            addCriterion("MSG like", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotLike(String value) {
            addCriterion("MSG not like", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgIn(List<String> values) {
            addCriterion("MSG in", values, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotIn(List<String> values) {
            addCriterion("MSG not in", values, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgBetween(String value1, String value2) {
            addCriterion("MSG between", value1, value2, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotBetween(String value1, String value2) {
            addCriterion("MSG not between", value1, value2, "msg");
            return (Criteria) this;
        }

        public Criteria andCnCodeIdIsNull() {
            addCriterion("CN_CODE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCnCodeIdIsNotNull() {
            addCriterion("CN_CODE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCnCodeIdEqualTo(String value) {
            addCriterion("CN_CODE_ID =", value, "cnCodeId");
            return (Criteria) this;
        }

        public Criteria andCnCodeIdNotEqualTo(String value) {
            addCriterion("CN_CODE_ID <>", value, "cnCodeId");
            return (Criteria) this;
        }

        public Criteria andCnCodeIdGreaterThan(String value) {
            addCriterion("CN_CODE_ID >", value, "cnCodeId");
            return (Criteria) this;
        }

        public Criteria andCnCodeIdGreaterThanOrEqualTo(String value) {
            addCriterion("CN_CODE_ID >=", value, "cnCodeId");
            return (Criteria) this;
        }

        public Criteria andCnCodeIdLessThan(String value) {
            addCriterion("CN_CODE_ID <", value, "cnCodeId");
            return (Criteria) this;
        }

        public Criteria andCnCodeIdLessThanOrEqualTo(String value) {
            addCriterion("CN_CODE_ID <=", value, "cnCodeId");
            return (Criteria) this;
        }

        public Criteria andCnCodeIdLike(String value) {
            addCriterion("CN_CODE_ID like", value, "cnCodeId");
            return (Criteria) this;
        }

        public Criteria andCnCodeIdNotLike(String value) {
            addCriterion("CN_CODE_ID not like", value, "cnCodeId");
            return (Criteria) this;
        }

        public Criteria andCnCodeIdIn(List<String> values) {
            addCriterion("CN_CODE_ID in", values, "cnCodeId");
            return (Criteria) this;
        }

        public Criteria andCnCodeIdNotIn(List<String> values) {
            addCriterion("CN_CODE_ID not in", values, "cnCodeId");
            return (Criteria) this;
        }

        public Criteria andCnCodeIdBetween(String value1, String value2) {
            addCriterion("CN_CODE_ID between", value1, value2, "cnCodeId");
            return (Criteria) this;
        }

        public Criteria andCnCodeIdNotBetween(String value1, String value2) {
            addCriterion("CN_CODE_ID not between", value1, value2, "cnCodeId");
            return (Criteria) this;
        }

        public Criteria andCnCodeIsNull() {
            addCriterion("CN_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCnCodeIsNotNull() {
            addCriterion("CN_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCnCodeEqualTo(String value) {
            addCriterion("CN_CODE =", value, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeNotEqualTo(String value) {
            addCriterion("CN_CODE <>", value, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeGreaterThan(String value) {
            addCriterion("CN_CODE >", value, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CN_CODE >=", value, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeLessThan(String value) {
            addCriterion("CN_CODE <", value, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeLessThanOrEqualTo(String value) {
            addCriterion("CN_CODE <=", value, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeLike(String value) {
            addCriterion("CN_CODE like", value, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeNotLike(String value) {
            addCriterion("CN_CODE not like", value, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeIn(List<String> values) {
            addCriterion("CN_CODE in", values, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeNotIn(List<String> values) {
            addCriterion("CN_CODE not in", values, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeBetween(String value1, String value2) {
            addCriterion("CN_CODE between", value1, value2, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeNotBetween(String value1, String value2) {
            addCriterion("CN_CODE not between", value1, value2, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeNameIsNull() {
            addCriterion("`CN_CODE _NAME` is null");
            return (Criteria) this;
        }

        public Criteria andCnCodeNameIsNotNull() {
            addCriterion("`CN_CODE _NAME` is not null");
            return (Criteria) this;
        }

        public Criteria andCnCodeNameEqualTo(String value) {
            addCriterion("`CN_CODE _NAME` =", value, "cnCodeName");
            return (Criteria) this;
        }

        public Criteria andCnCodeNameNotEqualTo(String value) {
            addCriterion("`CN_CODE _NAME` <>", value, "cnCodeName");
            return (Criteria) this;
        }

        public Criteria andCnCodeNameGreaterThan(String value) {
            addCriterion("`CN_CODE _NAME` >", value, "cnCodeName");
            return (Criteria) this;
        }

        public Criteria andCnCodeNameGreaterThanOrEqualTo(String value) {
            addCriterion("`CN_CODE _NAME` >=", value, "cnCodeName");
            return (Criteria) this;
        }

        public Criteria andCnCodeNameLessThan(String value) {
            addCriterion("`CN_CODE _NAME` <", value, "cnCodeName");
            return (Criteria) this;
        }

        public Criteria andCnCodeNameLessThanOrEqualTo(String value) {
            addCriterion("`CN_CODE _NAME` <=", value, "cnCodeName");
            return (Criteria) this;
        }

        public Criteria andCnCodeNameLike(String value) {
            addCriterion("`CN_CODE _NAME` like", value, "cnCodeName");
            return (Criteria) this;
        }

        public Criteria andCnCodeNameNotLike(String value) {
            addCriterion("`CN_CODE _NAME` not like", value, "cnCodeName");
            return (Criteria) this;
        }

        public Criteria andCnCodeNameIn(List<String> values) {
            addCriterion("`CN_CODE _NAME` in", values, "cnCodeName");
            return (Criteria) this;
        }

        public Criteria andCnCodeNameNotIn(List<String> values) {
            addCriterion("`CN_CODE _NAME` not in", values, "cnCodeName");
            return (Criteria) this;
        }

        public Criteria andCnCodeNameBetween(String value1, String value2) {
            addCriterion("`CN_CODE _NAME` between", value1, value2, "cnCodeName");
            return (Criteria) this;
        }

        public Criteria andCnCodeNameNotBetween(String value1, String value2) {
            addCriterion("`CN_CODE _NAME` not between", value1, value2, "cnCodeName");
            return (Criteria) this;
        }

        public Criteria andCnCodeMsgIsNull() {
            addCriterion("`CN_CODE _MSG` is null");
            return (Criteria) this;
        }

        public Criteria andCnCodeMsgIsNotNull() {
            addCriterion("`CN_CODE _MSG` is not null");
            return (Criteria) this;
        }

        public Criteria andCnCodeMsgEqualTo(String value) {
            addCriterion("`CN_CODE _MSG` =", value, "cnCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCnCodeMsgNotEqualTo(String value) {
            addCriterion("`CN_CODE _MSG` <>", value, "cnCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCnCodeMsgGreaterThan(String value) {
            addCriterion("`CN_CODE _MSG` >", value, "cnCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCnCodeMsgGreaterThanOrEqualTo(String value) {
            addCriterion("`CN_CODE _MSG` >=", value, "cnCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCnCodeMsgLessThan(String value) {
            addCriterion("`CN_CODE _MSG` <", value, "cnCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCnCodeMsgLessThanOrEqualTo(String value) {
            addCriterion("`CN_CODE _MSG` <=", value, "cnCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCnCodeMsgLike(String value) {
            addCriterion("`CN_CODE _MSG` like", value, "cnCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCnCodeMsgNotLike(String value) {
            addCriterion("`CN_CODE _MSG` not like", value, "cnCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCnCodeMsgIn(List<String> values) {
            addCriterion("`CN_CODE _MSG` in", values, "cnCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCnCodeMsgNotIn(List<String> values) {
            addCriterion("`CN_CODE _MSG` not in", values, "cnCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCnCodeMsgBetween(String value1, String value2) {
            addCriterion("`CN_CODE _MSG` between", value1, value2, "cnCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCnCodeMsgNotBetween(String value1, String value2) {
            addCriterion("`CN_CODE _MSG` not between", value1, value2, "cnCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCtCodeIdIsNull() {
            addCriterion("`CT_CODE _ID` is null");
            return (Criteria) this;
        }

        public Criteria andCtCodeIdIsNotNull() {
            addCriterion("`CT_CODE _ID` is not null");
            return (Criteria) this;
        }

        public Criteria andCtCodeIdEqualTo(String value) {
            addCriterion("`CT_CODE _ID` =", value, "ctCodeId");
            return (Criteria) this;
        }

        public Criteria andCtCodeIdNotEqualTo(String value) {
            addCriterion("`CT_CODE _ID` <>", value, "ctCodeId");
            return (Criteria) this;
        }

        public Criteria andCtCodeIdGreaterThan(String value) {
            addCriterion("`CT_CODE _ID` >", value, "ctCodeId");
            return (Criteria) this;
        }

        public Criteria andCtCodeIdGreaterThanOrEqualTo(String value) {
            addCriterion("`CT_CODE _ID` >=", value, "ctCodeId");
            return (Criteria) this;
        }

        public Criteria andCtCodeIdLessThan(String value) {
            addCriterion("`CT_CODE _ID` <", value, "ctCodeId");
            return (Criteria) this;
        }

        public Criteria andCtCodeIdLessThanOrEqualTo(String value) {
            addCriterion("`CT_CODE _ID` <=", value, "ctCodeId");
            return (Criteria) this;
        }

        public Criteria andCtCodeIdLike(String value) {
            addCriterion("`CT_CODE _ID` like", value, "ctCodeId");
            return (Criteria) this;
        }

        public Criteria andCtCodeIdNotLike(String value) {
            addCriterion("`CT_CODE _ID` not like", value, "ctCodeId");
            return (Criteria) this;
        }

        public Criteria andCtCodeIdIn(List<String> values) {
            addCriterion("`CT_CODE _ID` in", values, "ctCodeId");
            return (Criteria) this;
        }

        public Criteria andCtCodeIdNotIn(List<String> values) {
            addCriterion("`CT_CODE _ID` not in", values, "ctCodeId");
            return (Criteria) this;
        }

        public Criteria andCtCodeIdBetween(String value1, String value2) {
            addCriterion("`CT_CODE _ID` between", value1, value2, "ctCodeId");
            return (Criteria) this;
        }

        public Criteria andCtCodeIdNotBetween(String value1, String value2) {
            addCriterion("`CT_CODE _ID` not between", value1, value2, "ctCodeId");
            return (Criteria) this;
        }

        public Criteria andCtCodeIsNull() {
            addCriterion("CT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCtCodeIsNotNull() {
            addCriterion("CT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCtCodeEqualTo(String value) {
            addCriterion("CT_CODE =", value, "ctCode");
            return (Criteria) this;
        }

        public Criteria andCtCodeNotEqualTo(String value) {
            addCriterion("CT_CODE <>", value, "ctCode");
            return (Criteria) this;
        }

        public Criteria andCtCodeGreaterThan(String value) {
            addCriterion("CT_CODE >", value, "ctCode");
            return (Criteria) this;
        }

        public Criteria andCtCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CT_CODE >=", value, "ctCode");
            return (Criteria) this;
        }

        public Criteria andCtCodeLessThan(String value) {
            addCriterion("CT_CODE <", value, "ctCode");
            return (Criteria) this;
        }

        public Criteria andCtCodeLessThanOrEqualTo(String value) {
            addCriterion("CT_CODE <=", value, "ctCode");
            return (Criteria) this;
        }

        public Criteria andCtCodeLike(String value) {
            addCriterion("CT_CODE like", value, "ctCode");
            return (Criteria) this;
        }

        public Criteria andCtCodeNotLike(String value) {
            addCriterion("CT_CODE not like", value, "ctCode");
            return (Criteria) this;
        }

        public Criteria andCtCodeIn(List<String> values) {
            addCriterion("CT_CODE in", values, "ctCode");
            return (Criteria) this;
        }

        public Criteria andCtCodeNotIn(List<String> values) {
            addCriterion("CT_CODE not in", values, "ctCode");
            return (Criteria) this;
        }

        public Criteria andCtCodeBetween(String value1, String value2) {
            addCriterion("CT_CODE between", value1, value2, "ctCode");
            return (Criteria) this;
        }

        public Criteria andCtCodeNotBetween(String value1, String value2) {
            addCriterion("CT_CODE not between", value1, value2, "ctCode");
            return (Criteria) this;
        }

        public Criteria andCtCodeNameIsNull() {
            addCriterion("`CT_CODE _NAME` is null");
            return (Criteria) this;
        }

        public Criteria andCtCodeNameIsNotNull() {
            addCriterion("`CT_CODE _NAME` is not null");
            return (Criteria) this;
        }

        public Criteria andCtCodeNameEqualTo(String value) {
            addCriterion("`CT_CODE _NAME` =", value, "ctCodeName");
            return (Criteria) this;
        }

        public Criteria andCtCodeNameNotEqualTo(String value) {
            addCriterion("`CT_CODE _NAME` <>", value, "ctCodeName");
            return (Criteria) this;
        }

        public Criteria andCtCodeNameGreaterThan(String value) {
            addCriterion("`CT_CODE _NAME` >", value, "ctCodeName");
            return (Criteria) this;
        }

        public Criteria andCtCodeNameGreaterThanOrEqualTo(String value) {
            addCriterion("`CT_CODE _NAME` >=", value, "ctCodeName");
            return (Criteria) this;
        }

        public Criteria andCtCodeNameLessThan(String value) {
            addCriterion("`CT_CODE _NAME` <", value, "ctCodeName");
            return (Criteria) this;
        }

        public Criteria andCtCodeNameLessThanOrEqualTo(String value) {
            addCriterion("`CT_CODE _NAME` <=", value, "ctCodeName");
            return (Criteria) this;
        }

        public Criteria andCtCodeNameLike(String value) {
            addCriterion("`CT_CODE _NAME` like", value, "ctCodeName");
            return (Criteria) this;
        }

        public Criteria andCtCodeNameNotLike(String value) {
            addCriterion("`CT_CODE _NAME` not like", value, "ctCodeName");
            return (Criteria) this;
        }

        public Criteria andCtCodeNameIn(List<String> values) {
            addCriterion("`CT_CODE _NAME` in", values, "ctCodeName");
            return (Criteria) this;
        }

        public Criteria andCtCodeNameNotIn(List<String> values) {
            addCriterion("`CT_CODE _NAME` not in", values, "ctCodeName");
            return (Criteria) this;
        }

        public Criteria andCtCodeNameBetween(String value1, String value2) {
            addCriterion("`CT_CODE _NAME` between", value1, value2, "ctCodeName");
            return (Criteria) this;
        }

        public Criteria andCtCodeNameNotBetween(String value1, String value2) {
            addCriterion("`CT_CODE _NAME` not between", value1, value2, "ctCodeName");
            return (Criteria) this;
        }

        public Criteria andCtCodeMsgIsNull() {
            addCriterion("`CT_CODE _MSG` is null");
            return (Criteria) this;
        }

        public Criteria andCtCodeMsgIsNotNull() {
            addCriterion("`CT_CODE _MSG` is not null");
            return (Criteria) this;
        }

        public Criteria andCtCodeMsgEqualTo(String value) {
            addCriterion("`CT_CODE _MSG` =", value, "ctCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCtCodeMsgNotEqualTo(String value) {
            addCriterion("`CT_CODE _MSG` <>", value, "ctCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCtCodeMsgGreaterThan(String value) {
            addCriterion("`CT_CODE _MSG` >", value, "ctCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCtCodeMsgGreaterThanOrEqualTo(String value) {
            addCriterion("`CT_CODE _MSG` >=", value, "ctCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCtCodeMsgLessThan(String value) {
            addCriterion("`CT_CODE _MSG` <", value, "ctCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCtCodeMsgLessThanOrEqualTo(String value) {
            addCriterion("`CT_CODE _MSG` <=", value, "ctCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCtCodeMsgLike(String value) {
            addCriterion("`CT_CODE _MSG` like", value, "ctCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCtCodeMsgNotLike(String value) {
            addCriterion("`CT_CODE _MSG` not like", value, "ctCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCtCodeMsgIn(List<String> values) {
            addCriterion("`CT_CODE _MSG` in", values, "ctCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCtCodeMsgNotIn(List<String> values) {
            addCriterion("`CT_CODE _MSG` not in", values, "ctCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCtCodeMsgBetween(String value1, String value2) {
            addCriterion("`CT_CODE _MSG` between", value1, value2, "ctCodeMsg");
            return (Criteria) this;
        }

        public Criteria andCtCodeMsgNotBetween(String value1, String value2) {
            addCriterion("`CT_CODE _MSG` not between", value1, value2, "ctCodeMsg");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("NOTE is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("NOTE is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("NOTE =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("NOTE <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("NOTE >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("NOTE >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("NOTE <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("NOTE <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("NOTE like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("NOTE not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("NOTE in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("NOTE not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("NOTE between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("NOTE not between", value1, value2, "note");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_err_code
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_err_code
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}