package com.ums.mbr.service.core.example;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class HisPaymentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hispayment
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hispayment
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hispayment
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hispayment
     *
     * @mbg.generated
     */
    public HisPaymentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hispayment
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hispayment
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hispayment
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hispayment
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hispayment
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hispayment
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hispayment
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hispayment
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hispayment
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hispayment
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hispayment
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRetserialIsNull() {
            addCriterion("RETSERIAL is null");
            return (Criteria) this;
        }

        public Criteria andRetserialIsNotNull() {
            addCriterion("RETSERIAL is not null");
            return (Criteria) this;
        }

        public Criteria andRetserialEqualTo(String value) {
            addCriterion("RETSERIAL =", value, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialNotEqualTo(String value) {
            addCriterion("RETSERIAL <>", value, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialGreaterThan(String value) {
            addCriterion("RETSERIAL >", value, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialGreaterThanOrEqualTo(String value) {
            addCriterion("RETSERIAL >=", value, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialLessThan(String value) {
            addCriterion("RETSERIAL <", value, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialLessThanOrEqualTo(String value) {
            addCriterion("RETSERIAL <=", value, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialLike(String value) {
            addCriterion("RETSERIAL like", value, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialNotLike(String value) {
            addCriterion("RETSERIAL not like", value, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialIn(List<String> values) {
            addCriterion("RETSERIAL in", values, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialNotIn(List<String> values) {
            addCriterion("RETSERIAL not in", values, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialBetween(String value1, String value2) {
            addCriterion("RETSERIAL between", value1, value2, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialNotBetween(String value1, String value2) {
            addCriterion("RETSERIAL not between", value1, value2, "retserial");
            return (Criteria) this;
        }

        public Criteria andMchtnoIsNull() {
            addCriterion("MCHTNO is null");
            return (Criteria) this;
        }

        public Criteria andMchtnoIsNotNull() {
            addCriterion("MCHTNO is not null");
            return (Criteria) this;
        }

        public Criteria andMchtnoEqualTo(String value) {
            addCriterion("MCHTNO =", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoNotEqualTo(String value) {
            addCriterion("MCHTNO <>", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoGreaterThan(String value) {
            addCriterion("MCHTNO >", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoGreaterThanOrEqualTo(String value) {
            addCriterion("MCHTNO >=", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoLessThan(String value) {
            addCriterion("MCHTNO <", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoLessThanOrEqualTo(String value) {
            addCriterion("MCHTNO <=", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoLike(String value) {
            addCriterion("MCHTNO like", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoNotLike(String value) {
            addCriterion("MCHTNO not like", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoIn(List<String> values) {
            addCriterion("MCHTNO in", values, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoNotIn(List<String> values) {
            addCriterion("MCHTNO not in", values, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoBetween(String value1, String value2) {
            addCriterion("MCHTNO between", value1, value2, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoNotBetween(String value1, String value2) {
            addCriterion("MCHTNO not between", value1, value2, "mchtno");
            return (Criteria) this;
        }

        public Criteria andTermnoIsNull() {
            addCriterion("TERMNO is null");
            return (Criteria) this;
        }

        public Criteria andTermnoIsNotNull() {
            addCriterion("TERMNO is not null");
            return (Criteria) this;
        }

        public Criteria andTermnoEqualTo(String value) {
            addCriterion("TERMNO =", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoNotEqualTo(String value) {
            addCriterion("TERMNO <>", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoGreaterThan(String value) {
            addCriterion("TERMNO >", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoGreaterThanOrEqualTo(String value) {
            addCriterion("TERMNO >=", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoLessThan(String value) {
            addCriterion("TERMNO <", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoLessThanOrEqualTo(String value) {
            addCriterion("TERMNO <=", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoLike(String value) {
            addCriterion("TERMNO like", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoNotLike(String value) {
            addCriterion("TERMNO not like", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoIn(List<String> values) {
            addCriterion("TERMNO in", values, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoNotIn(List<String> values) {
            addCriterion("TERMNO not in", values, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoBetween(String value1, String value2) {
            addCriterion("TERMNO between", value1, value2, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoNotBetween(String value1, String value2) {
            addCriterion("TERMNO not between", value1, value2, "termno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoIsNull() {
            addCriterion("EXMCHTNO is null");
            return (Criteria) this;
        }

        public Criteria andExmchtnoIsNotNull() {
            addCriterion("EXMCHTNO is not null");
            return (Criteria) this;
        }

        public Criteria andExmchtnoEqualTo(String value) {
            addCriterion("EXMCHTNO =", value, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoNotEqualTo(String value) {
            addCriterion("EXMCHTNO <>", value, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoGreaterThan(String value) {
            addCriterion("EXMCHTNO >", value, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoGreaterThanOrEqualTo(String value) {
            addCriterion("EXMCHTNO >=", value, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoLessThan(String value) {
            addCriterion("EXMCHTNO <", value, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoLessThanOrEqualTo(String value) {
            addCriterion("EXMCHTNO <=", value, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoLike(String value) {
            addCriterion("EXMCHTNO like", value, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoNotLike(String value) {
            addCriterion("EXMCHTNO not like", value, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoIn(List<String> values) {
            addCriterion("EXMCHTNO in", values, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoNotIn(List<String> values) {
            addCriterion("EXMCHTNO not in", values, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoBetween(String value1, String value2) {
            addCriterion("EXMCHTNO between", value1, value2, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoNotBetween(String value1, String value2) {
            addCriterion("EXMCHTNO not between", value1, value2, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExtermnoIsNull() {
            addCriterion("EXTERMNO is null");
            return (Criteria) this;
        }

        public Criteria andExtermnoIsNotNull() {
            addCriterion("EXTERMNO is not null");
            return (Criteria) this;
        }

        public Criteria andExtermnoEqualTo(String value) {
            addCriterion("EXTERMNO =", value, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoNotEqualTo(String value) {
            addCriterion("EXTERMNO <>", value, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoGreaterThan(String value) {
            addCriterion("EXTERMNO >", value, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoGreaterThanOrEqualTo(String value) {
            addCriterion("EXTERMNO >=", value, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoLessThan(String value) {
            addCriterion("EXTERMNO <", value, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoLessThanOrEqualTo(String value) {
            addCriterion("EXTERMNO <=", value, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoLike(String value) {
            addCriterion("EXTERMNO like", value, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoNotLike(String value) {
            addCriterion("EXTERMNO not like", value, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoIn(List<String> values) {
            addCriterion("EXTERMNO in", values, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoNotIn(List<String> values) {
            addCriterion("EXTERMNO not in", values, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoBetween(String value1, String value2) {
            addCriterion("EXTERMNO between", value1, value2, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoNotBetween(String value1, String value2) {
            addCriterion("EXTERMNO not between", value1, value2, "extermno");
            return (Criteria) this;
        }

        public Criteria andTradeNoIsNull() {
            addCriterion("TRADE_NO is null");
            return (Criteria) this;
        }

        public Criteria andTradeNoIsNotNull() {
            addCriterion("TRADE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andTradeNoEqualTo(String value) {
            addCriterion("TRADE_NO =", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotEqualTo(String value) {
            addCriterion("TRADE_NO <>", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoGreaterThan(String value) {
            addCriterion("TRADE_NO >", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_NO >=", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoLessThan(String value) {
            addCriterion("TRADE_NO <", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoLessThanOrEqualTo(String value) {
            addCriterion("TRADE_NO <=", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoLike(String value) {
            addCriterion("TRADE_NO like", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotLike(String value) {
            addCriterion("TRADE_NO not like", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoIn(List<String> values) {
            addCriterion("TRADE_NO in", values, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotIn(List<String> values) {
            addCriterion("TRADE_NO not in", values, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoBetween(String value1, String value2) {
            addCriterion("TRADE_NO between", value1, value2, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotBetween(String value1, String value2) {
            addCriterion("TRADE_NO not between", value1, value2, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIsNull() {
            addCriterion("OUT_TRADE_NO is null");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIsNotNull() {
            addCriterion("OUT_TRADE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoEqualTo(String value) {
            addCriterion("OUT_TRADE_NO =", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotEqualTo(String value) {
            addCriterion("OUT_TRADE_NO <>", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoGreaterThan(String value) {
            addCriterion("OUT_TRADE_NO >", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoGreaterThanOrEqualTo(String value) {
            addCriterion("OUT_TRADE_NO >=", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLessThan(String value) {
            addCriterion("OUT_TRADE_NO <", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLessThanOrEqualTo(String value) {
            addCriterion("OUT_TRADE_NO <=", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLike(String value) {
            addCriterion("OUT_TRADE_NO like", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotLike(String value) {
            addCriterion("OUT_TRADE_NO not like", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIn(List<String> values) {
            addCriterion("OUT_TRADE_NO in", values, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotIn(List<String> values) {
            addCriterion("OUT_TRADE_NO not in", values, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoBetween(String value1, String value2) {
            addCriterion("OUT_TRADE_NO between", value1, value2, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotBetween(String value1, String value2) {
            addCriterion("OUT_TRADE_NO not between", value1, value2, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("ORDER_NO =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("ORDER_NO <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("ORDER_NO >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_NO >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("ORDER_NO <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("ORDER_NO <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("ORDER_NO like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("ORDER_NO not like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("ORDER_NO in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("ORDER_NO not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("ORDER_NO between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("ORDER_NO not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andPaymentOrderNoIsNull() {
            addCriterion("PAYMENT_ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andPaymentOrderNoIsNotNull() {
            addCriterion("PAYMENT_ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentOrderNoEqualTo(String value) {
            addCriterion("PAYMENT_ORDER_NO =", value, "paymentOrderNo");
            return (Criteria) this;
        }

        public Criteria andPaymentOrderNoNotEqualTo(String value) {
            addCriterion("PAYMENT_ORDER_NO <>", value, "paymentOrderNo");
            return (Criteria) this;
        }

        public Criteria andPaymentOrderNoGreaterThan(String value) {
            addCriterion("PAYMENT_ORDER_NO >", value, "paymentOrderNo");
            return (Criteria) this;
        }

        public Criteria andPaymentOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("PAYMENT_ORDER_NO >=", value, "paymentOrderNo");
            return (Criteria) this;
        }

        public Criteria andPaymentOrderNoLessThan(String value) {
            addCriterion("PAYMENT_ORDER_NO <", value, "paymentOrderNo");
            return (Criteria) this;
        }

        public Criteria andPaymentOrderNoLessThanOrEqualTo(String value) {
            addCriterion("PAYMENT_ORDER_NO <=", value, "paymentOrderNo");
            return (Criteria) this;
        }

        public Criteria andPaymentOrderNoLike(String value) {
            addCriterion("PAYMENT_ORDER_NO like", value, "paymentOrderNo");
            return (Criteria) this;
        }

        public Criteria andPaymentOrderNoNotLike(String value) {
            addCriterion("PAYMENT_ORDER_NO not like", value, "paymentOrderNo");
            return (Criteria) this;
        }

        public Criteria andPaymentOrderNoIn(List<String> values) {
            addCriterion("PAYMENT_ORDER_NO in", values, "paymentOrderNo");
            return (Criteria) this;
        }

        public Criteria andPaymentOrderNoNotIn(List<String> values) {
            addCriterion("PAYMENT_ORDER_NO not in", values, "paymentOrderNo");
            return (Criteria) this;
        }

        public Criteria andPaymentOrderNoBetween(String value1, String value2) {
            addCriterion("PAYMENT_ORDER_NO between", value1, value2, "paymentOrderNo");
            return (Criteria) this;
        }

        public Criteria andPaymentOrderNoNotBetween(String value1, String value2) {
            addCriterion("PAYMENT_ORDER_NO not between", value1, value2, "paymentOrderNo");
            return (Criteria) this;
        }

        public Criteria andCenterNoIsNull() {
            addCriterion("CENTER_NO is null");
            return (Criteria) this;
        }

        public Criteria andCenterNoIsNotNull() {
            addCriterion("CENTER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCenterNoEqualTo(String value) {
            addCriterion("CENTER_NO =", value, "centerNo");
            return (Criteria) this;
        }

        public Criteria andCenterNoNotEqualTo(String value) {
            addCriterion("CENTER_NO <>", value, "centerNo");
            return (Criteria) this;
        }

        public Criteria andCenterNoGreaterThan(String value) {
            addCriterion("CENTER_NO >", value, "centerNo");
            return (Criteria) this;
        }

        public Criteria andCenterNoGreaterThanOrEqualTo(String value) {
            addCriterion("CENTER_NO >=", value, "centerNo");
            return (Criteria) this;
        }

        public Criteria andCenterNoLessThan(String value) {
            addCriterion("CENTER_NO <", value, "centerNo");
            return (Criteria) this;
        }

        public Criteria andCenterNoLessThanOrEqualTo(String value) {
            addCriterion("CENTER_NO <=", value, "centerNo");
            return (Criteria) this;
        }

        public Criteria andCenterNoLike(String value) {
            addCriterion("CENTER_NO like", value, "centerNo");
            return (Criteria) this;
        }

        public Criteria andCenterNoNotLike(String value) {
            addCriterion("CENTER_NO not like", value, "centerNo");
            return (Criteria) this;
        }

        public Criteria andCenterNoIn(List<String> values) {
            addCriterion("CENTER_NO in", values, "centerNo");
            return (Criteria) this;
        }

        public Criteria andCenterNoNotIn(List<String> values) {
            addCriterion("CENTER_NO not in", values, "centerNo");
            return (Criteria) this;
        }

        public Criteria andCenterNoBetween(String value1, String value2) {
            addCriterion("CENTER_NO between", value1, value2, "centerNo");
            return (Criteria) this;
        }

        public Criteria andCenterNoNotBetween(String value1, String value2) {
            addCriterion("CENTER_NO not between", value1, value2, "centerNo");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeIsNull() {
            addCriterion("CUSTOMER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeIsNotNull() {
            addCriterion("CUSTOMER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeEqualTo(String value) {
            addCriterion("CUSTOMER_TYPE =", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeNotEqualTo(String value) {
            addCriterion("CUSTOMER_TYPE <>", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeGreaterThan(String value) {
            addCriterion("CUSTOMER_TYPE >", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTOMER_TYPE >=", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeLessThan(String value) {
            addCriterion("CUSTOMER_TYPE <", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeLessThanOrEqualTo(String value) {
            addCriterion("CUSTOMER_TYPE <=", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeLike(String value) {
            addCriterion("CUSTOMER_TYPE like", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeNotLike(String value) {
            addCriterion("CUSTOMER_TYPE not like", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeIn(List<String> values) {
            addCriterion("CUSTOMER_TYPE in", values, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeNotIn(List<String> values) {
            addCriterion("CUSTOMER_TYPE not in", values, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeBetween(String value1, String value2) {
            addCriterion("CUSTOMER_TYPE between", value1, value2, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeNotBetween(String value1, String value2) {
            addCriterion("CUSTOMER_TYPE not between", value1, value2, "customerType");
            return (Criteria) this;
        }

        public Criteria andCurrencyIsNull() {
            addCriterion("CURRENCY is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyIsNotNull() {
            addCriterion("CURRENCY is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyEqualTo(String value) {
            addCriterion("CURRENCY =", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotEqualTo(String value) {
            addCriterion("CURRENCY <>", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyGreaterThan(String value) {
            addCriterion("CURRENCY >", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("CURRENCY >=", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLessThan(String value) {
            addCriterion("CURRENCY <", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLessThanOrEqualTo(String value) {
            addCriterion("CURRENCY <=", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLike(String value) {
            addCriterion("CURRENCY like", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotLike(String value) {
            addCriterion("CURRENCY not like", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyIn(List<String> values) {
            addCriterion("CURRENCY in", values, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotIn(List<String> values) {
            addCriterion("CURRENCY not in", values, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyBetween(String value1, String value2) {
            addCriterion("CURRENCY between", value1, value2, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotBetween(String value1, String value2) {
            addCriterion("CURRENCY not between", value1, value2, "currency");
            return (Criteria) this;
        }

        public Criteria andRealAmountIsNull() {
            addCriterion("REAL_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andRealAmountIsNotNull() {
            addCriterion("REAL_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andRealAmountEqualTo(BigDecimal value) {
            addCriterion("REAL_AMOUNT =", value, "realAmount");
            return (Criteria) this;
        }

        public Criteria andRealAmountNotEqualTo(BigDecimal value) {
            addCriterion("REAL_AMOUNT <>", value, "realAmount");
            return (Criteria) this;
        }

        public Criteria andRealAmountGreaterThan(BigDecimal value) {
            addCriterion("REAL_AMOUNT >", value, "realAmount");
            return (Criteria) this;
        }

        public Criteria andRealAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("REAL_AMOUNT >=", value, "realAmount");
            return (Criteria) this;
        }

        public Criteria andRealAmountLessThan(BigDecimal value) {
            addCriterion("REAL_AMOUNT <", value, "realAmount");
            return (Criteria) this;
        }

        public Criteria andRealAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("REAL_AMOUNT <=", value, "realAmount");
            return (Criteria) this;
        }

        public Criteria andRealAmountIn(List<BigDecimal> values) {
            addCriterion("REAL_AMOUNT in", values, "realAmount");
            return (Criteria) this;
        }

        public Criteria andRealAmountNotIn(List<BigDecimal> values) {
            addCriterion("REAL_AMOUNT not in", values, "realAmount");
            return (Criteria) this;
        }

        public Criteria andRealAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REAL_AMOUNT between", value1, value2, "realAmount");
            return (Criteria) this;
        }

        public Criteria andRealAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REAL_AMOUNT not between", value1, value2, "realAmount");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeIsNull() {
            addCriterion("PAY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andPayTimeIsNotNull() {
            addCriterion("PAY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andPayTimeEqualTo(String value) {
            addCriterion("PAY_TIME =", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotEqualTo(String value) {
            addCriterion("PAY_TIME <>", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeGreaterThan(String value) {
            addCriterion("PAY_TIME >", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_TIME >=", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeLessThan(String value) {
            addCriterion("PAY_TIME <", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeLessThanOrEqualTo(String value) {
            addCriterion("PAY_TIME <=", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeLike(String value) {
            addCriterion("PAY_TIME like", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotLike(String value) {
            addCriterion("PAY_TIME not like", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeIn(List<String> values) {
            addCriterion("PAY_TIME in", values, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotIn(List<String> values) {
            addCriterion("PAY_TIME not in", values, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeBetween(String value1, String value2) {
            addCriterion("PAY_TIME between", value1, value2, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotBetween(String value1, String value2) {
            addCriterion("PAY_TIME not between", value1, value2, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayCodeIsNull() {
            addCriterion("PAY_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPayCodeIsNotNull() {
            addCriterion("PAY_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPayCodeEqualTo(String value) {
            addCriterion("PAY_CODE =", value, "payCode");
            return (Criteria) this;
        }

        public Criteria andPayCodeNotEqualTo(String value) {
            addCriterion("PAY_CODE <>", value, "payCode");
            return (Criteria) this;
        }

        public Criteria andPayCodeGreaterThan(String value) {
            addCriterion("PAY_CODE >", value, "payCode");
            return (Criteria) this;
        }

        public Criteria andPayCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_CODE >=", value, "payCode");
            return (Criteria) this;
        }

        public Criteria andPayCodeLessThan(String value) {
            addCriterion("PAY_CODE <", value, "payCode");
            return (Criteria) this;
        }

        public Criteria andPayCodeLessThanOrEqualTo(String value) {
            addCriterion("PAY_CODE <=", value, "payCode");
            return (Criteria) this;
        }

        public Criteria andPayCodeLike(String value) {
            addCriterion("PAY_CODE like", value, "payCode");
            return (Criteria) this;
        }

        public Criteria andPayCodeNotLike(String value) {
            addCriterion("PAY_CODE not like", value, "payCode");
            return (Criteria) this;
        }

        public Criteria andPayCodeIn(List<String> values) {
            addCriterion("PAY_CODE in", values, "payCode");
            return (Criteria) this;
        }

        public Criteria andPayCodeNotIn(List<String> values) {
            addCriterion("PAY_CODE not in", values, "payCode");
            return (Criteria) this;
        }

        public Criteria andPayCodeBetween(String value1, String value2) {
            addCriterion("PAY_CODE between", value1, value2, "payCode");
            return (Criteria) this;
        }

        public Criteria andPayCodeNotBetween(String value1, String value2) {
            addCriterion("PAY_CODE not between", value1, value2, "payCode");
            return (Criteria) this;
        }

        public Criteria andBatchnoIsNull() {
            addCriterion("BATCHNO is null");
            return (Criteria) this;
        }

        public Criteria andBatchnoIsNotNull() {
            addCriterion("BATCHNO is not null");
            return (Criteria) this;
        }

        public Criteria andBatchnoEqualTo(String value) {
            addCriterion("BATCHNO =", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoNotEqualTo(String value) {
            addCriterion("BATCHNO <>", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoGreaterThan(String value) {
            addCriterion("BATCHNO >", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoGreaterThanOrEqualTo(String value) {
            addCriterion("BATCHNO >=", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoLessThan(String value) {
            addCriterion("BATCHNO <", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoLessThanOrEqualTo(String value) {
            addCriterion("BATCHNO <=", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoLike(String value) {
            addCriterion("BATCHNO like", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoNotLike(String value) {
            addCriterion("BATCHNO not like", value, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoIn(List<String> values) {
            addCriterion("BATCHNO in", values, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoNotIn(List<String> values) {
            addCriterion("BATCHNO not in", values, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoBetween(String value1, String value2) {
            addCriterion("BATCHNO between", value1, value2, "batchno");
            return (Criteria) this;
        }

        public Criteria andBatchnoNotBetween(String value1, String value2) {
            addCriterion("BATCHNO not between", value1, value2, "batchno");
            return (Criteria) this;
        }

        public Criteria andTracenoIsNull() {
            addCriterion("TRACENO is null");
            return (Criteria) this;
        }

        public Criteria andTracenoIsNotNull() {
            addCriterion("TRACENO is not null");
            return (Criteria) this;
        }

        public Criteria andTracenoEqualTo(String value) {
            addCriterion("TRACENO =", value, "traceno");
            return (Criteria) this;
        }

        public Criteria andTracenoNotEqualTo(String value) {
            addCriterion("TRACENO <>", value, "traceno");
            return (Criteria) this;
        }

        public Criteria andTracenoGreaterThan(String value) {
            addCriterion("TRACENO >", value, "traceno");
            return (Criteria) this;
        }

        public Criteria andTracenoGreaterThanOrEqualTo(String value) {
            addCriterion("TRACENO >=", value, "traceno");
            return (Criteria) this;
        }

        public Criteria andTracenoLessThan(String value) {
            addCriterion("TRACENO <", value, "traceno");
            return (Criteria) this;
        }

        public Criteria andTracenoLessThanOrEqualTo(String value) {
            addCriterion("TRACENO <=", value, "traceno");
            return (Criteria) this;
        }

        public Criteria andTracenoLike(String value) {
            addCriterion("TRACENO like", value, "traceno");
            return (Criteria) this;
        }

        public Criteria andTracenoNotLike(String value) {
            addCriterion("TRACENO not like", value, "traceno");
            return (Criteria) this;
        }

        public Criteria andTracenoIn(List<String> values) {
            addCriterion("TRACENO in", values, "traceno");
            return (Criteria) this;
        }

        public Criteria andTracenoNotIn(List<String> values) {
            addCriterion("TRACENO not in", values, "traceno");
            return (Criteria) this;
        }

        public Criteria andTracenoBetween(String value1, String value2) {
            addCriterion("TRACENO between", value1, value2, "traceno");
            return (Criteria) this;
        }

        public Criteria andTracenoNotBetween(String value1, String value2) {
            addCriterion("TRACENO not between", value1, value2, "traceno");
            return (Criteria) this;
        }

        public Criteria andRefernceNoIsNull() {
            addCriterion("REFERNCE_NO is null");
            return (Criteria) this;
        }

        public Criteria andRefernceNoIsNotNull() {
            addCriterion("REFERNCE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andRefernceNoEqualTo(String value) {
            addCriterion("REFERNCE_NO =", value, "refernceNo");
            return (Criteria) this;
        }

        public Criteria andRefernceNoNotEqualTo(String value) {
            addCriterion("REFERNCE_NO <>", value, "refernceNo");
            return (Criteria) this;
        }

        public Criteria andRefernceNoGreaterThan(String value) {
            addCriterion("REFERNCE_NO >", value, "refernceNo");
            return (Criteria) this;
        }

        public Criteria andRefernceNoGreaterThanOrEqualTo(String value) {
            addCriterion("REFERNCE_NO >=", value, "refernceNo");
            return (Criteria) this;
        }

        public Criteria andRefernceNoLessThan(String value) {
            addCriterion("REFERNCE_NO <", value, "refernceNo");
            return (Criteria) this;
        }

        public Criteria andRefernceNoLessThanOrEqualTo(String value) {
            addCriterion("REFERNCE_NO <=", value, "refernceNo");
            return (Criteria) this;
        }

        public Criteria andRefernceNoLike(String value) {
            addCriterion("REFERNCE_NO like", value, "refernceNo");
            return (Criteria) this;
        }

        public Criteria andRefernceNoNotLike(String value) {
            addCriterion("REFERNCE_NO not like", value, "refernceNo");
            return (Criteria) this;
        }

        public Criteria andRefernceNoIn(List<String> values) {
            addCriterion("REFERNCE_NO in", values, "refernceNo");
            return (Criteria) this;
        }

        public Criteria andRefernceNoNotIn(List<String> values) {
            addCriterion("REFERNCE_NO not in", values, "refernceNo");
            return (Criteria) this;
        }

        public Criteria andRefernceNoBetween(String value1, String value2) {
            addCriterion("REFERNCE_NO between", value1, value2, "refernceNo");
            return (Criteria) this;
        }

        public Criteria andRefernceNoNotBetween(String value1, String value2) {
            addCriterion("REFERNCE_NO not between", value1, value2, "refernceNo");
            return (Criteria) this;
        }

        public Criteria andRetcodeIsNull() {
            addCriterion("RETCODE is null");
            return (Criteria) this;
        }

        public Criteria andRetcodeIsNotNull() {
            addCriterion("RETCODE is not null");
            return (Criteria) this;
        }

        public Criteria andRetcodeEqualTo(String value) {
            addCriterion("RETCODE =", value, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeNotEqualTo(String value) {
            addCriterion("RETCODE <>", value, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeGreaterThan(String value) {
            addCriterion("RETCODE >", value, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeGreaterThanOrEqualTo(String value) {
            addCriterion("RETCODE >=", value, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeLessThan(String value) {
            addCriterion("RETCODE <", value, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeLessThanOrEqualTo(String value) {
            addCriterion("RETCODE <=", value, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeLike(String value) {
            addCriterion("RETCODE like", value, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeNotLike(String value) {
            addCriterion("RETCODE not like", value, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeIn(List<String> values) {
            addCriterion("RETCODE in", values, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeNotIn(List<String> values) {
            addCriterion("RETCODE not in", values, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeBetween(String value1, String value2) {
            addCriterion("RETCODE between", value1, value2, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeNotBetween(String value1, String value2) {
            addCriterion("RETCODE not between", value1, value2, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetmsgIsNull() {
            addCriterion("RETMSG is null");
            return (Criteria) this;
        }

        public Criteria andRetmsgIsNotNull() {
            addCriterion("RETMSG is not null");
            return (Criteria) this;
        }

        public Criteria andRetmsgEqualTo(String value) {
            addCriterion("RETMSG =", value, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgNotEqualTo(String value) {
            addCriterion("RETMSG <>", value, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgGreaterThan(String value) {
            addCriterion("RETMSG >", value, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgGreaterThanOrEqualTo(String value) {
            addCriterion("RETMSG >=", value, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgLessThan(String value) {
            addCriterion("RETMSG <", value, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgLessThanOrEqualTo(String value) {
            addCriterion("RETMSG <=", value, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgLike(String value) {
            addCriterion("RETMSG like", value, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgNotLike(String value) {
            addCriterion("RETMSG not like", value, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgIn(List<String> values) {
            addCriterion("RETMSG in", values, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgNotIn(List<String> values) {
            addCriterion("RETMSG not in", values, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgBetween(String value1, String value2) {
            addCriterion("RETMSG between", value1, value2, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgNotBetween(String value1, String value2) {
            addCriterion("RETMSG not between", value1, value2, "retmsg");
            return (Criteria) this;
        }

        public Criteria andCreateIpIsNull() {
            addCriterion("CREATE_IP is null");
            return (Criteria) this;
        }

        public Criteria andCreateIpIsNotNull() {
            addCriterion("CREATE_IP is not null");
            return (Criteria) this;
        }

        public Criteria andCreateIpEqualTo(String value) {
            addCriterion("CREATE_IP =", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpNotEqualTo(String value) {
            addCriterion("CREATE_IP <>", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpGreaterThan(String value) {
            addCriterion("CREATE_IP >", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_IP >=", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpLessThan(String value) {
            addCriterion("CREATE_IP <", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpLessThanOrEqualTo(String value) {
            addCriterion("CREATE_IP <=", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpLike(String value) {
            addCriterion("CREATE_IP like", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpNotLike(String value) {
            addCriterion("CREATE_IP not like", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpIn(List<String> values) {
            addCriterion("CREATE_IP in", values, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpNotIn(List<String> values) {
            addCriterion("CREATE_IP not in", values, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpBetween(String value1, String value2) {
            addCriterion("CREATE_IP between", value1, value2, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpNotBetween(String value1, String value2) {
            addCriterion("CREATE_IP not between", value1, value2, "createIp");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlIsNull() {
            addCriterion("NOTIFY_URL is null");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlIsNotNull() {
            addCriterion("NOTIFY_URL is not null");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlEqualTo(String value) {
            addCriterion("NOTIFY_URL =", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlNotEqualTo(String value) {
            addCriterion("NOTIFY_URL <>", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlGreaterThan(String value) {
            addCriterion("NOTIFY_URL >", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlGreaterThanOrEqualTo(String value) {
            addCriterion("NOTIFY_URL >=", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlLessThan(String value) {
            addCriterion("NOTIFY_URL <", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlLessThanOrEqualTo(String value) {
            addCriterion("NOTIFY_URL <=", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlLike(String value) {
            addCriterion("NOTIFY_URL like", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlNotLike(String value) {
            addCriterion("NOTIFY_URL not like", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlIn(List<String> values) {
            addCriterion("NOTIFY_URL in", values, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlNotIn(List<String> values) {
            addCriterion("NOTIFY_URL not in", values, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlBetween(String value1, String value2) {
            addCriterion("NOTIFY_URL between", value1, value2, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlNotBetween(String value1, String value2) {
            addCriterion("NOTIFY_URL not between", value1, value2, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("SOURCE is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("SOURCE is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("SOURCE =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("SOURCE <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("SOURCE >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("SOURCE <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("SOURCE <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("SOURCE like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("SOURCE not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("SOURCE in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("SOURCE not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("SOURCE between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("SOURCE not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNull() {
            addCriterion("SUBJECT is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNotNull() {
            addCriterion("SUBJECT is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectEqualTo(String value) {
            addCriterion("SUBJECT =", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotEqualTo(String value) {
            addCriterion("SUBJECT <>", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThan(String value) {
            addCriterion("SUBJECT >", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("SUBJECT >=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThan(String value) {
            addCriterion("SUBJECT <", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThanOrEqualTo(String value) {
            addCriterion("SUBJECT <=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLike(String value) {
            addCriterion("SUBJECT like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotLike(String value) {
            addCriterion("SUBJECT not like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectIn(List<String> values) {
            addCriterion("SUBJECT in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotIn(List<String> values) {
            addCriterion("SUBJECT not in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectBetween(String value1, String value2) {
            addCriterion("SUBJECT between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotBetween(String value1, String value2) {
            addCriterion("SUBJECT not between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailIsNull() {
            addCriterion("GOODS_DETAIL is null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailIsNotNull() {
            addCriterion("GOODS_DETAIL is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailEqualTo(String value) {
            addCriterion("GOODS_DETAIL =", value, "goodsDetail");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailNotEqualTo(String value) {
            addCriterion("GOODS_DETAIL <>", value, "goodsDetail");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailGreaterThan(String value) {
            addCriterion("GOODS_DETAIL >", value, "goodsDetail");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailGreaterThanOrEqualTo(String value) {
            addCriterion("GOODS_DETAIL >=", value, "goodsDetail");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailLessThan(String value) {
            addCriterion("GOODS_DETAIL <", value, "goodsDetail");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailLessThanOrEqualTo(String value) {
            addCriterion("GOODS_DETAIL <=", value, "goodsDetail");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailLike(String value) {
            addCriterion("GOODS_DETAIL like", value, "goodsDetail");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailNotLike(String value) {
            addCriterion("GOODS_DETAIL not like", value, "goodsDetail");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailIn(List<String> values) {
            addCriterion("GOODS_DETAIL in", values, "goodsDetail");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailNotIn(List<String> values) {
            addCriterion("GOODS_DETAIL not in", values, "goodsDetail");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailBetween(String value1, String value2) {
            addCriterion("GOODS_DETAIL between", value1, value2, "goodsDetail");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailNotBetween(String value1, String value2) {
            addCriterion("GOODS_DETAIL not between", value1, value2, "goodsDetail");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("NOTE is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("NOTE is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("NOTE =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("NOTE <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("NOTE >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("NOTE >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("NOTE <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("NOTE <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("NOTE like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("NOTE not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("NOTE in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("NOTE not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("NOTE between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("NOTE not between", value1, value2, "note");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hispayment
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_hispayment
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}