package com.ums.mbr.service.core.example;

import java.util.ArrayList;
import java.util.List;

public class TermExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    public TermExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMchtnoIsNull() {
            addCriterion("MCHTNO is null");
            return (Criteria) this;
        }

        public Criteria andMchtnoIsNotNull() {
            addCriterion("MCHTNO is not null");
            return (Criteria) this;
        }

        public Criteria andMchtnoEqualTo(String value) {
            addCriterion("MCHTNO =", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoNotEqualTo(String value) {
            addCriterion("MCHTNO <>", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoGreaterThan(String value) {
            addCriterion("MCHTNO >", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoGreaterThanOrEqualTo(String value) {
            addCriterion("MCHTNO >=", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoLessThan(String value) {
            addCriterion("MCHTNO <", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoLessThanOrEqualTo(String value) {
            addCriterion("MCHTNO <=", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoLike(String value) {
            addCriterion("MCHTNO like", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoNotLike(String value) {
            addCriterion("MCHTNO not like", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoIn(List<String> values) {
            addCriterion("MCHTNO in", values, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoNotIn(List<String> values) {
            addCriterion("MCHTNO not in", values, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoBetween(String value1, String value2) {
            addCriterion("MCHTNO between", value1, value2, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoNotBetween(String value1, String value2) {
            addCriterion("MCHTNO not between", value1, value2, "mchtno");
            return (Criteria) this;
        }

        public Criteria andTermnoIsNull() {
            addCriterion("TERMNO is null");
            return (Criteria) this;
        }

        public Criteria andTermnoIsNotNull() {
            addCriterion("TERMNO is not null");
            return (Criteria) this;
        }

        public Criteria andTermnoEqualTo(String value) {
            addCriterion("TERMNO =", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoNotEqualTo(String value) {
            addCriterion("TERMNO <>", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoGreaterThan(String value) {
            addCriterion("TERMNO >", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoGreaterThanOrEqualTo(String value) {
            addCriterion("TERMNO >=", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoLessThan(String value) {
            addCriterion("TERMNO <", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoLessThanOrEqualTo(String value) {
            addCriterion("TERMNO <=", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoLike(String value) {
            addCriterion("TERMNO like", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoNotLike(String value) {
            addCriterion("TERMNO not like", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoIn(List<String> values) {
            addCriterion("TERMNO in", values, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoNotIn(List<String> values) {
            addCriterion("TERMNO not in", values, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoBetween(String value1, String value2) {
            addCriterion("TERMNO between", value1, value2, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoNotBetween(String value1, String value2) {
            addCriterion("TERMNO not between", value1, value2, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnameIsNull() {
            addCriterion("TERMNAME is null");
            return (Criteria) this;
        }

        public Criteria andTermnameIsNotNull() {
            addCriterion("TERMNAME is not null");
            return (Criteria) this;
        }

        public Criteria andTermnameEqualTo(String value) {
            addCriterion("TERMNAME =", value, "termname");
            return (Criteria) this;
        }

        public Criteria andTermnameNotEqualTo(String value) {
            addCriterion("TERMNAME <>", value, "termname");
            return (Criteria) this;
        }

        public Criteria andTermnameGreaterThan(String value) {
            addCriterion("TERMNAME >", value, "termname");
            return (Criteria) this;
        }

        public Criteria andTermnameGreaterThanOrEqualTo(String value) {
            addCriterion("TERMNAME >=", value, "termname");
            return (Criteria) this;
        }

        public Criteria andTermnameLessThan(String value) {
            addCriterion("TERMNAME <", value, "termname");
            return (Criteria) this;
        }

        public Criteria andTermnameLessThanOrEqualTo(String value) {
            addCriterion("TERMNAME <=", value, "termname");
            return (Criteria) this;
        }

        public Criteria andTermnameLike(String value) {
            addCriterion("TERMNAME like", value, "termname");
            return (Criteria) this;
        }

        public Criteria andTermnameNotLike(String value) {
            addCriterion("TERMNAME not like", value, "termname");
            return (Criteria) this;
        }

        public Criteria andTermnameIn(List<String> values) {
            addCriterion("TERMNAME in", values, "termname");
            return (Criteria) this;
        }

        public Criteria andTermnameNotIn(List<String> values) {
            addCriterion("TERMNAME not in", values, "termname");
            return (Criteria) this;
        }

        public Criteria andTermnameBetween(String value1, String value2) {
            addCriterion("TERMNAME between", value1, value2, "termname");
            return (Criteria) this;
        }

        public Criteria andTermnameNotBetween(String value1, String value2) {
            addCriterion("TERMNAME not between", value1, value2, "termname");
            return (Criteria) this;
        }

        public Criteria andSignTypeIsNull() {
            addCriterion("SIGN_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSignTypeIsNotNull() {
            addCriterion("SIGN_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSignTypeEqualTo(String value) {
            addCriterion("SIGN_TYPE =", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeNotEqualTo(String value) {
            addCriterion("SIGN_TYPE <>", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeGreaterThan(String value) {
            addCriterion("SIGN_TYPE >", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SIGN_TYPE >=", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeLessThan(String value) {
            addCriterion("SIGN_TYPE <", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeLessThanOrEqualTo(String value) {
            addCriterion("SIGN_TYPE <=", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeLike(String value) {
            addCriterion("SIGN_TYPE like", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeNotLike(String value) {
            addCriterion("SIGN_TYPE not like", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeIn(List<String> values) {
            addCriterion("SIGN_TYPE in", values, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeNotIn(List<String> values) {
            addCriterion("SIGN_TYPE not in", values, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeBetween(String value1, String value2) {
            addCriterion("SIGN_TYPE between", value1, value2, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeNotBetween(String value1, String value2) {
            addCriterion("SIGN_TYPE not between", value1, value2, "signType");
            return (Criteria) this;
        }

        public Criteria andPublicKeyIsNull() {
            addCriterion("PUBLIC_KEY is null");
            return (Criteria) this;
        }

        public Criteria andPublicKeyIsNotNull() {
            addCriterion("PUBLIC_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andPublicKeyEqualTo(String value) {
            addCriterion("PUBLIC_KEY =", value, "publicKey");
            return (Criteria) this;
        }

        public Criteria andPublicKeyNotEqualTo(String value) {
            addCriterion("PUBLIC_KEY <>", value, "publicKey");
            return (Criteria) this;
        }

        public Criteria andPublicKeyGreaterThan(String value) {
            addCriterion("PUBLIC_KEY >", value, "publicKey");
            return (Criteria) this;
        }

        public Criteria andPublicKeyGreaterThanOrEqualTo(String value) {
            addCriterion("PUBLIC_KEY >=", value, "publicKey");
            return (Criteria) this;
        }

        public Criteria andPublicKeyLessThan(String value) {
            addCriterion("PUBLIC_KEY <", value, "publicKey");
            return (Criteria) this;
        }

        public Criteria andPublicKeyLessThanOrEqualTo(String value) {
            addCriterion("PUBLIC_KEY <=", value, "publicKey");
            return (Criteria) this;
        }

        public Criteria andPublicKeyLike(String value) {
            addCriterion("PUBLIC_KEY like", value, "publicKey");
            return (Criteria) this;
        }

        public Criteria andPublicKeyNotLike(String value) {
            addCriterion("PUBLIC_KEY not like", value, "publicKey");
            return (Criteria) this;
        }

        public Criteria andPublicKeyIn(List<String> values) {
            addCriterion("PUBLIC_KEY in", values, "publicKey");
            return (Criteria) this;
        }

        public Criteria andPublicKeyNotIn(List<String> values) {
            addCriterion("PUBLIC_KEY not in", values, "publicKey");
            return (Criteria) this;
        }

        public Criteria andPublicKeyBetween(String value1, String value2) {
            addCriterion("PUBLIC_KEY between", value1, value2, "publicKey");
            return (Criteria) this;
        }

        public Criteria andPublicKeyNotBetween(String value1, String value2) {
            addCriterion("PUBLIC_KEY not between", value1, value2, "publicKey");
            return (Criteria) this;
        }

        public Criteria andPrivateKeyIsNull() {
            addCriterion("PRIVATE_KEY is null");
            return (Criteria) this;
        }

        public Criteria andPrivateKeyIsNotNull() {
            addCriterion("PRIVATE_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andPrivateKeyEqualTo(String value) {
            addCriterion("PRIVATE_KEY =", value, "privateKey");
            return (Criteria) this;
        }

        public Criteria andPrivateKeyNotEqualTo(String value) {
            addCriterion("PRIVATE_KEY <>", value, "privateKey");
            return (Criteria) this;
        }

        public Criteria andPrivateKeyGreaterThan(String value) {
            addCriterion("PRIVATE_KEY >", value, "privateKey");
            return (Criteria) this;
        }

        public Criteria andPrivateKeyGreaterThanOrEqualTo(String value) {
            addCriterion("PRIVATE_KEY >=", value, "privateKey");
            return (Criteria) this;
        }

        public Criteria andPrivateKeyLessThan(String value) {
            addCriterion("PRIVATE_KEY <", value, "privateKey");
            return (Criteria) this;
        }

        public Criteria andPrivateKeyLessThanOrEqualTo(String value) {
            addCriterion("PRIVATE_KEY <=", value, "privateKey");
            return (Criteria) this;
        }

        public Criteria andPrivateKeyLike(String value) {
            addCriterion("PRIVATE_KEY like", value, "privateKey");
            return (Criteria) this;
        }

        public Criteria andPrivateKeyNotLike(String value) {
            addCriterion("PRIVATE_KEY not like", value, "privateKey");
            return (Criteria) this;
        }

        public Criteria andPrivateKeyIn(List<String> values) {
            addCriterion("PRIVATE_KEY in", values, "privateKey");
            return (Criteria) this;
        }

        public Criteria andPrivateKeyNotIn(List<String> values) {
            addCriterion("PRIVATE_KEY not in", values, "privateKey");
            return (Criteria) this;
        }

        public Criteria andPrivateKeyBetween(String value1, String value2) {
            addCriterion("PRIVATE_KEY between", value1, value2, "privateKey");
            return (Criteria) this;
        }

        public Criteria andPrivateKeyNotBetween(String value1, String value2) {
            addCriterion("PRIVATE_KEY not between", value1, value2, "privateKey");
            return (Criteria) this;
        }

        public Criteria andMd5keyIsNull() {
            addCriterion("MD5KEY is null");
            return (Criteria) this;
        }

        public Criteria andMd5keyIsNotNull() {
            addCriterion("MD5KEY is not null");
            return (Criteria) this;
        }

        public Criteria andMd5keyEqualTo(String value) {
            addCriterion("MD5KEY =", value, "md5key");
            return (Criteria) this;
        }

        public Criteria andMd5keyNotEqualTo(String value) {
            addCriterion("MD5KEY <>", value, "md5key");
            return (Criteria) this;
        }

        public Criteria andMd5keyGreaterThan(String value) {
            addCriterion("MD5KEY >", value, "md5key");
            return (Criteria) this;
        }

        public Criteria andMd5keyGreaterThanOrEqualTo(String value) {
            addCriterion("MD5KEY >=", value, "md5key");
            return (Criteria) this;
        }

        public Criteria andMd5keyLessThan(String value) {
            addCriterion("MD5KEY <", value, "md5key");
            return (Criteria) this;
        }

        public Criteria andMd5keyLessThanOrEqualTo(String value) {
            addCriterion("MD5KEY <=", value, "md5key");
            return (Criteria) this;
        }

        public Criteria andMd5keyLike(String value) {
            addCriterion("MD5KEY like", value, "md5key");
            return (Criteria) this;
        }

        public Criteria andMd5keyNotLike(String value) {
            addCriterion("MD5KEY not like", value, "md5key");
            return (Criteria) this;
        }

        public Criteria andMd5keyIn(List<String> values) {
            addCriterion("MD5KEY in", values, "md5key");
            return (Criteria) this;
        }

        public Criteria andMd5keyNotIn(List<String> values) {
            addCriterion("MD5KEY not in", values, "md5key");
            return (Criteria) this;
        }

        public Criteria andMd5keyBetween(String value1, String value2) {
            addCriterion("MD5KEY between", value1, value2, "md5key");
            return (Criteria) this;
        }

        public Criteria andMd5keyNotBetween(String value1, String value2) {
            addCriterion("MD5KEY not between", value1, value2, "md5key");
            return (Criteria) this;
        }

        public Criteria andRefundFlagIsNull() {
            addCriterion("REFUND_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andRefundFlagIsNotNull() {
            addCriterion("REFUND_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andRefundFlagEqualTo(String value) {
            addCriterion("REFUND_FLAG =", value, "refundFlag");
            return (Criteria) this;
        }

        public Criteria andRefundFlagNotEqualTo(String value) {
            addCriterion("REFUND_FLAG <>", value, "refundFlag");
            return (Criteria) this;
        }

        public Criteria andRefundFlagGreaterThan(String value) {
            addCriterion("REFUND_FLAG >", value, "refundFlag");
            return (Criteria) this;
        }

        public Criteria andRefundFlagGreaterThanOrEqualTo(String value) {
            addCriterion("REFUND_FLAG >=", value, "refundFlag");
            return (Criteria) this;
        }

        public Criteria andRefundFlagLessThan(String value) {
            addCriterion("REFUND_FLAG <", value, "refundFlag");
            return (Criteria) this;
        }

        public Criteria andRefundFlagLessThanOrEqualTo(String value) {
            addCriterion("REFUND_FLAG <=", value, "refundFlag");
            return (Criteria) this;
        }

        public Criteria andRefundFlagLike(String value) {
            addCriterion("REFUND_FLAG like", value, "refundFlag");
            return (Criteria) this;
        }

        public Criteria andRefundFlagNotLike(String value) {
            addCriterion("REFUND_FLAG not like", value, "refundFlag");
            return (Criteria) this;
        }

        public Criteria andRefundFlagIn(List<String> values) {
            addCriterion("REFUND_FLAG in", values, "refundFlag");
            return (Criteria) this;
        }

        public Criteria andRefundFlagNotIn(List<String> values) {
            addCriterion("REFUND_FLAG not in", values, "refundFlag");
            return (Criteria) this;
        }

        public Criteria andRefundFlagBetween(String value1, String value2) {
            addCriterion("REFUND_FLAG between", value1, value2, "refundFlag");
            return (Criteria) this;
        }

        public Criteria andRefundFlagNotBetween(String value1, String value2) {
            addCriterion("REFUND_FLAG not between", value1, value2, "refundFlag");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andRefreshTimeIsNull() {
            addCriterion("REFRESH_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRefreshTimeIsNotNull() {
            addCriterion("REFRESH_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRefreshTimeEqualTo(String value) {
            addCriterion("REFRESH_TIME =", value, "refreshTime");
            return (Criteria) this;
        }

        public Criteria andRefreshTimeNotEqualTo(String value) {
            addCriterion("REFRESH_TIME <>", value, "refreshTime");
            return (Criteria) this;
        }

        public Criteria andRefreshTimeGreaterThan(String value) {
            addCriterion("REFRESH_TIME >", value, "refreshTime");
            return (Criteria) this;
        }

        public Criteria andRefreshTimeGreaterThanOrEqualTo(String value) {
            addCriterion("REFRESH_TIME >=", value, "refreshTime");
            return (Criteria) this;
        }

        public Criteria andRefreshTimeLessThan(String value) {
            addCriterion("REFRESH_TIME <", value, "refreshTime");
            return (Criteria) this;
        }

        public Criteria andRefreshTimeLessThanOrEqualTo(String value) {
            addCriterion("REFRESH_TIME <=", value, "refreshTime");
            return (Criteria) this;
        }

        public Criteria andRefreshTimeLike(String value) {
            addCriterion("REFRESH_TIME like", value, "refreshTime");
            return (Criteria) this;
        }

        public Criteria andRefreshTimeNotLike(String value) {
            addCriterion("REFRESH_TIME not like", value, "refreshTime");
            return (Criteria) this;
        }

        public Criteria andRefreshTimeIn(List<String> values) {
            addCriterion("REFRESH_TIME in", values, "refreshTime");
            return (Criteria) this;
        }

        public Criteria andRefreshTimeNotIn(List<String> values) {
            addCriterion("REFRESH_TIME not in", values, "refreshTime");
            return (Criteria) this;
        }

        public Criteria andRefreshTimeBetween(String value1, String value2) {
            addCriterion("REFRESH_TIME between", value1, value2, "refreshTime");
            return (Criteria) this;
        }

        public Criteria andRefreshTimeNotBetween(String value1, String value2) {
            addCriterion("REFRESH_TIME not between", value1, value2, "refreshTime");
            return (Criteria) this;
        }

        public Criteria andOtaCountIsNull() {
            addCriterion("OTA_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andOtaCountIsNotNull() {
            addCriterion("OTA_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andOtaCountEqualTo(Integer value) {
            addCriterion("OTA_COUNT =", value, "otaCount");
            return (Criteria) this;
        }

        public Criteria andOtaCountNotEqualTo(Integer value) {
            addCriterion("OTA_COUNT <>", value, "otaCount");
            return (Criteria) this;
        }

        public Criteria andOtaCountGreaterThan(Integer value) {
            addCriterion("OTA_COUNT >", value, "otaCount");
            return (Criteria) this;
        }

        public Criteria andOtaCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("OTA_COUNT >=", value, "otaCount");
            return (Criteria) this;
        }

        public Criteria andOtaCountLessThan(Integer value) {
            addCriterion("OTA_COUNT <", value, "otaCount");
            return (Criteria) this;
        }

        public Criteria andOtaCountLessThanOrEqualTo(Integer value) {
            addCriterion("OTA_COUNT <=", value, "otaCount");
            return (Criteria) this;
        }

        public Criteria andOtaCountIn(List<Integer> values) {
            addCriterion("OTA_COUNT in", values, "otaCount");
            return (Criteria) this;
        }

        public Criteria andOtaCountNotIn(List<Integer> values) {
            addCriterion("OTA_COUNT not in", values, "otaCount");
            return (Criteria) this;
        }

        public Criteria andOtaCountBetween(Integer value1, Integer value2) {
            addCriterion("OTA_COUNT between", value1, value2, "otaCount");
            return (Criteria) this;
        }

        public Criteria andOtaCountNotBetween(Integer value1, Integer value2) {
            addCriterion("OTA_COUNT not between", value1, value2, "otaCount");
            return (Criteria) this;
        }

        public Criteria andOtaAdmitIsNull() {
            addCriterion("OTA_ADMIT is null");
            return (Criteria) this;
        }

        public Criteria andOtaAdmitIsNotNull() {
            addCriterion("OTA_ADMIT is not null");
            return (Criteria) this;
        }

        public Criteria andOtaAdmitEqualTo(Integer value) {
            addCriterion("OTA_ADMIT =", value, "otaAdmit");
            return (Criteria) this;
        }

        public Criteria andOtaAdmitNotEqualTo(Integer value) {
            addCriterion("OTA_ADMIT <>", value, "otaAdmit");
            return (Criteria) this;
        }

        public Criteria andOtaAdmitGreaterThan(Integer value) {
            addCriterion("OTA_ADMIT >", value, "otaAdmit");
            return (Criteria) this;
        }

        public Criteria andOtaAdmitGreaterThanOrEqualTo(Integer value) {
            addCriterion("OTA_ADMIT >=", value, "otaAdmit");
            return (Criteria) this;
        }

        public Criteria andOtaAdmitLessThan(Integer value) {
            addCriterion("OTA_ADMIT <", value, "otaAdmit");
            return (Criteria) this;
        }

        public Criteria andOtaAdmitLessThanOrEqualTo(Integer value) {
            addCriterion("OTA_ADMIT <=", value, "otaAdmit");
            return (Criteria) this;
        }

        public Criteria andOtaAdmitIn(List<Integer> values) {
            addCriterion("OTA_ADMIT in", values, "otaAdmit");
            return (Criteria) this;
        }

        public Criteria andOtaAdmitNotIn(List<Integer> values) {
            addCriterion("OTA_ADMIT not in", values, "otaAdmit");
            return (Criteria) this;
        }

        public Criteria andOtaAdmitBetween(Integer value1, Integer value2) {
            addCriterion("OTA_ADMIT between", value1, value2, "otaAdmit");
            return (Criteria) this;
        }

        public Criteria andOtaAdmitNotBetween(Integer value1, Integer value2) {
            addCriterion("OTA_ADMIT not between", value1, value2, "otaAdmit");
            return (Criteria) this;
        }

        public Criteria andOtaTimeIsNull() {
            addCriterion("OTA_TIME is null");
            return (Criteria) this;
        }

        public Criteria andOtaTimeIsNotNull() {
            addCriterion("OTA_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andOtaTimeEqualTo(String value) {
            addCriterion("OTA_TIME =", value, "otaTime");
            return (Criteria) this;
        }

        public Criteria andOtaTimeNotEqualTo(String value) {
            addCriterion("OTA_TIME <>", value, "otaTime");
            return (Criteria) this;
        }

        public Criteria andOtaTimeGreaterThan(String value) {
            addCriterion("OTA_TIME >", value, "otaTime");
            return (Criteria) this;
        }

        public Criteria andOtaTimeGreaterThanOrEqualTo(String value) {
            addCriterion("OTA_TIME >=", value, "otaTime");
            return (Criteria) this;
        }

        public Criteria andOtaTimeLessThan(String value) {
            addCriterion("OTA_TIME <", value, "otaTime");
            return (Criteria) this;
        }

        public Criteria andOtaTimeLessThanOrEqualTo(String value) {
            addCriterion("OTA_TIME <=", value, "otaTime");
            return (Criteria) this;
        }

        public Criteria andOtaTimeLike(String value) {
            addCriterion("OTA_TIME like", value, "otaTime");
            return (Criteria) this;
        }

        public Criteria andOtaTimeNotLike(String value) {
            addCriterion("OTA_TIME not like", value, "otaTime");
            return (Criteria) this;
        }

        public Criteria andOtaTimeIn(List<String> values) {
            addCriterion("OTA_TIME in", values, "otaTime");
            return (Criteria) this;
        }

        public Criteria andOtaTimeNotIn(List<String> values) {
            addCriterion("OTA_TIME not in", values, "otaTime");
            return (Criteria) this;
        }

        public Criteria andOtaTimeBetween(String value1, String value2) {
            addCriterion("OTA_TIME between", value1, value2, "otaTime");
            return (Criteria) this;
        }

        public Criteria andOtaTimeNotBetween(String value1, String value2) {
            addCriterion("OTA_TIME not between", value1, value2, "otaTime");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("NOTE is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("NOTE is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("NOTE =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("NOTE <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("NOTE >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("NOTE >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("NOTE <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("NOTE <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("NOTE like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("NOTE not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("NOTE in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("NOTE not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("NOTE between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("NOTE not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andRouterIdIsNull() {
            addCriterion("ROUTER_ID is null");
            return (Criteria) this;
        }

        public Criteria andRouterIdIsNotNull() {
            addCriterion("ROUTER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRouterIdEqualTo(String value) {
            addCriterion("ROUTER_ID =", value, "routerId");
            return (Criteria) this;
        }

        public Criteria andRouterIdNotEqualTo(String value) {
            addCriterion("ROUTER_ID <>", value, "routerId");
            return (Criteria) this;
        }

        public Criteria andRouterIdGreaterThan(String value) {
            addCriterion("ROUTER_ID >", value, "routerId");
            return (Criteria) this;
        }

        public Criteria andRouterIdGreaterThanOrEqualTo(String value) {
            addCriterion("ROUTER_ID >=", value, "routerId");
            return (Criteria) this;
        }

        public Criteria andRouterIdLessThan(String value) {
            addCriterion("ROUTER_ID <", value, "routerId");
            return (Criteria) this;
        }

        public Criteria andRouterIdLessThanOrEqualTo(String value) {
            addCriterion("ROUTER_ID <=", value, "routerId");
            return (Criteria) this;
        }

        public Criteria andRouterIdLike(String value) {
            addCriterion("ROUTER_ID like", value, "routerId");
            return (Criteria) this;
        }

        public Criteria andRouterIdNotLike(String value) {
            addCriterion("ROUTER_ID not like", value, "routerId");
            return (Criteria) this;
        }

        public Criteria andRouterIdIn(List<String> values) {
            addCriterion("ROUTER_ID in", values, "routerId");
            return (Criteria) this;
        }

        public Criteria andRouterIdNotIn(List<String> values) {
            addCriterion("ROUTER_ID not in", values, "routerId");
            return (Criteria) this;
        }

        public Criteria andRouterIdBetween(String value1, String value2) {
            addCriterion("ROUTER_ID between", value1, value2, "routerId");
            return (Criteria) this;
        }

        public Criteria andRouterIdNotBetween(String value1, String value2) {
            addCriterion("ROUTER_ID not between", value1, value2, "routerId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table umsmember..t_term
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table umsmember..t_term
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}