package com.ums.mbr.service.core.example;

import java.util.ArrayList;
import java.util.List;

public class TransLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umsmember..t_translog
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umsmember..t_translog
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table umsmember..t_translog
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_translog
     *
     * @mbg.generated
     */
    public TransLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_translog
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_translog
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_translog
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_translog
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_translog
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_translog
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_translog
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_translog
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_translog
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table umsmember..t_translog
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table umsmember..t_translog
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRetserialIsNull() {
            addCriterion("RETSERIAL is null");
            return (Criteria) this;
        }

        public Criteria andRetserialIsNotNull() {
            addCriterion("RETSERIAL is not null");
            return (Criteria) this;
        }

        public Criteria andRetserialEqualTo(String value) {
            addCriterion("RETSERIAL =", value, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialNotEqualTo(String value) {
            addCriterion("RETSERIAL <>", value, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialGreaterThan(String value) {
            addCriterion("RETSERIAL >", value, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialGreaterThanOrEqualTo(String value) {
            addCriterion("RETSERIAL >=", value, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialLessThan(String value) {
            addCriterion("RETSERIAL <", value, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialLessThanOrEqualTo(String value) {
            addCriterion("RETSERIAL <=", value, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialLike(String value) {
            addCriterion("RETSERIAL like", value, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialNotLike(String value) {
            addCriterion("RETSERIAL not like", value, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialIn(List<String> values) {
            addCriterion("RETSERIAL in", values, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialNotIn(List<String> values) {
            addCriterion("RETSERIAL not in", values, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialBetween(String value1, String value2) {
            addCriterion("RETSERIAL between", value1, value2, "retserial");
            return (Criteria) this;
        }

        public Criteria andRetserialNotBetween(String value1, String value2) {
            addCriterion("RETSERIAL not between", value1, value2, "retserial");
            return (Criteria) this;
        }

        public Criteria andMchtnoIsNull() {
            addCriterion("MCHTNO is null");
            return (Criteria) this;
        }

        public Criteria andMchtnoIsNotNull() {
            addCriterion("MCHTNO is not null");
            return (Criteria) this;
        }

        public Criteria andMchtnoEqualTo(String value) {
            addCriterion("MCHTNO =", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoNotEqualTo(String value) {
            addCriterion("MCHTNO <>", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoGreaterThan(String value) {
            addCriterion("MCHTNO >", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoGreaterThanOrEqualTo(String value) {
            addCriterion("MCHTNO >=", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoLessThan(String value) {
            addCriterion("MCHTNO <", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoLessThanOrEqualTo(String value) {
            addCriterion("MCHTNO <=", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoLike(String value) {
            addCriterion("MCHTNO like", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoNotLike(String value) {
            addCriterion("MCHTNO not like", value, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoIn(List<String> values) {
            addCriterion("MCHTNO in", values, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoNotIn(List<String> values) {
            addCriterion("MCHTNO not in", values, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoBetween(String value1, String value2) {
            addCriterion("MCHTNO between", value1, value2, "mchtno");
            return (Criteria) this;
        }

        public Criteria andMchtnoNotBetween(String value1, String value2) {
            addCriterion("MCHTNO not between", value1, value2, "mchtno");
            return (Criteria) this;
        }

        public Criteria andTermnoIsNull() {
            addCriterion("TERMNO is null");
            return (Criteria) this;
        }

        public Criteria andTermnoIsNotNull() {
            addCriterion("TERMNO is not null");
            return (Criteria) this;
        }

        public Criteria andTermnoEqualTo(String value) {
            addCriterion("TERMNO =", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoNotEqualTo(String value) {
            addCriterion("TERMNO <>", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoGreaterThan(String value) {
            addCriterion("TERMNO >", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoGreaterThanOrEqualTo(String value) {
            addCriterion("TERMNO >=", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoLessThan(String value) {
            addCriterion("TERMNO <", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoLessThanOrEqualTo(String value) {
            addCriterion("TERMNO <=", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoLike(String value) {
            addCriterion("TERMNO like", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoNotLike(String value) {
            addCriterion("TERMNO not like", value, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoIn(List<String> values) {
            addCriterion("TERMNO in", values, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoNotIn(List<String> values) {
            addCriterion("TERMNO not in", values, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoBetween(String value1, String value2) {
            addCriterion("TERMNO between", value1, value2, "termno");
            return (Criteria) this;
        }

        public Criteria andTermnoNotBetween(String value1, String value2) {
            addCriterion("TERMNO not between", value1, value2, "termno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoIsNull() {
            addCriterion("EXMCHTNO is null");
            return (Criteria) this;
        }

        public Criteria andExmchtnoIsNotNull() {
            addCriterion("EXMCHTNO is not null");
            return (Criteria) this;
        }

        public Criteria andExmchtnoEqualTo(String value) {
            addCriterion("EXMCHTNO =", value, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoNotEqualTo(String value) {
            addCriterion("EXMCHTNO <>", value, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoGreaterThan(String value) {
            addCriterion("EXMCHTNO >", value, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoGreaterThanOrEqualTo(String value) {
            addCriterion("EXMCHTNO >=", value, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoLessThan(String value) {
            addCriterion("EXMCHTNO <", value, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoLessThanOrEqualTo(String value) {
            addCriterion("EXMCHTNO <=", value, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoLike(String value) {
            addCriterion("EXMCHTNO like", value, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoNotLike(String value) {
            addCriterion("EXMCHTNO not like", value, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoIn(List<String> values) {
            addCriterion("EXMCHTNO in", values, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoNotIn(List<String> values) {
            addCriterion("EXMCHTNO not in", values, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoBetween(String value1, String value2) {
            addCriterion("EXMCHTNO between", value1, value2, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExmchtnoNotBetween(String value1, String value2) {
            addCriterion("EXMCHTNO not between", value1, value2, "exmchtno");
            return (Criteria) this;
        }

        public Criteria andExtermnoIsNull() {
            addCriterion("EXTERMNO is null");
            return (Criteria) this;
        }

        public Criteria andExtermnoIsNotNull() {
            addCriterion("EXTERMNO is not null");
            return (Criteria) this;
        }

        public Criteria andExtermnoEqualTo(String value) {
            addCriterion("EXTERMNO =", value, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoNotEqualTo(String value) {
            addCriterion("EXTERMNO <>", value, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoGreaterThan(String value) {
            addCriterion("EXTERMNO >", value, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoGreaterThanOrEqualTo(String value) {
            addCriterion("EXTERMNO >=", value, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoLessThan(String value) {
            addCriterion("EXTERMNO <", value, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoLessThanOrEqualTo(String value) {
            addCriterion("EXTERMNO <=", value, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoLike(String value) {
            addCriterion("EXTERMNO like", value, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoNotLike(String value) {
            addCriterion("EXTERMNO not like", value, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoIn(List<String> values) {
            addCriterion("EXTERMNO in", values, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoNotIn(List<String> values) {
            addCriterion("EXTERMNO not in", values, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoBetween(String value1, String value2) {
            addCriterion("EXTERMNO between", value1, value2, "extermno");
            return (Criteria) this;
        }

        public Criteria andExtermnoNotBetween(String value1, String value2) {
            addCriterion("EXTERMNO not between", value1, value2, "extermno");
            return (Criteria) this;
        }

        public Criteria andRequestIdIsNull() {
            addCriterion("REQUEST_ID is null");
            return (Criteria) this;
        }

        public Criteria andRequestIdIsNotNull() {
            addCriterion("REQUEST_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRequestIdEqualTo(String value) {
            addCriterion("REQUEST_ID =", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotEqualTo(String value) {
            addCriterion("REQUEST_ID <>", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdGreaterThan(String value) {
            addCriterion("REQUEST_ID >", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdGreaterThanOrEqualTo(String value) {
            addCriterion("REQUEST_ID >=", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdLessThan(String value) {
            addCriterion("REQUEST_ID <", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdLessThanOrEqualTo(String value) {
            addCriterion("REQUEST_ID <=", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdLike(String value) {
            addCriterion("REQUEST_ID like", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotLike(String value) {
            addCriterion("REQUEST_ID not like", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdIn(List<String> values) {
            addCriterion("REQUEST_ID in", values, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotIn(List<String> values) {
            addCriterion("REQUEST_ID not in", values, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdBetween(String value1, String value2) {
            addCriterion("REQUEST_ID between", value1, value2, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotBetween(String value1, String value2) {
            addCriterion("REQUEST_ID not between", value1, value2, "requestId");
            return (Criteria) this;
        }

        public Criteria andTradeNoIsNull() {
            addCriterion("TRADE_NO is null");
            return (Criteria) this;
        }

        public Criteria andTradeNoIsNotNull() {
            addCriterion("TRADE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andTradeNoEqualTo(String value) {
            addCriterion("TRADE_NO =", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotEqualTo(String value) {
            addCriterion("TRADE_NO <>", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoGreaterThan(String value) {
            addCriterion("TRADE_NO >", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_NO >=", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoLessThan(String value) {
            addCriterion("TRADE_NO <", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoLessThanOrEqualTo(String value) {
            addCriterion("TRADE_NO <=", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoLike(String value) {
            addCriterion("TRADE_NO like", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotLike(String value) {
            addCriterion("TRADE_NO not like", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoIn(List<String> values) {
            addCriterion("TRADE_NO in", values, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotIn(List<String> values) {
            addCriterion("TRADE_NO not in", values, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoBetween(String value1, String value2) {
            addCriterion("TRADE_NO between", value1, value2, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotBetween(String value1, String value2) {
            addCriterion("TRADE_NO not between", value1, value2, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIsNull() {
            addCriterion("OUT_TRADE_NO is null");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIsNotNull() {
            addCriterion("OUT_TRADE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoEqualTo(String value) {
            addCriterion("OUT_TRADE_NO =", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotEqualTo(String value) {
            addCriterion("OUT_TRADE_NO <>", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoGreaterThan(String value) {
            addCriterion("OUT_TRADE_NO >", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoGreaterThanOrEqualTo(String value) {
            addCriterion("OUT_TRADE_NO >=", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLessThan(String value) {
            addCriterion("OUT_TRADE_NO <", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLessThanOrEqualTo(String value) {
            addCriterion("OUT_TRADE_NO <=", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLike(String value) {
            addCriterion("OUT_TRADE_NO like", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotLike(String value) {
            addCriterion("OUT_TRADE_NO not like", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIn(List<String> values) {
            addCriterion("OUT_TRADE_NO in", values, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotIn(List<String> values) {
            addCriterion("OUT_TRADE_NO not in", values, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoBetween(String value1, String value2) {
            addCriterion("OUT_TRADE_NO between", value1, value2, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotBetween(String value1, String value2) {
            addCriterion("OUT_TRADE_NO not between", value1, value2, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("ORDER_NO =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("ORDER_NO <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("ORDER_NO >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_NO >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("ORDER_NO <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("ORDER_NO <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("ORDER_NO like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("ORDER_NO not like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("ORDER_NO in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("ORDER_NO not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("ORDER_NO between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("ORDER_NO not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andBizTypeIsNull() {
            addCriterion("BIZ_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andBizTypeIsNotNull() {
            addCriterion("BIZ_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andBizTypeEqualTo(String value) {
            addCriterion("BIZ_TYPE =", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotEqualTo(String value) {
            addCriterion("BIZ_TYPE <>", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeGreaterThan(String value) {
            addCriterion("BIZ_TYPE >", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeGreaterThanOrEqualTo(String value) {
            addCriterion("BIZ_TYPE >=", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLessThan(String value) {
            addCriterion("BIZ_TYPE <", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLessThanOrEqualTo(String value) {
            addCriterion("BIZ_TYPE <=", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLike(String value) {
            addCriterion("BIZ_TYPE like", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotLike(String value) {
            addCriterion("BIZ_TYPE not like", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeIn(List<String> values) {
            addCriterion("BIZ_TYPE in", values, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotIn(List<String> values) {
            addCriterion("BIZ_TYPE not in", values, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeBetween(String value1, String value2) {
            addCriterion("BIZ_TYPE between", value1, value2, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotBetween(String value1, String value2) {
            addCriterion("BIZ_TYPE not between", value1, value2, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizChannelIsNull() {
            addCriterion("BIZ_CHANNEL is null");
            return (Criteria) this;
        }

        public Criteria andBizChannelIsNotNull() {
            addCriterion("BIZ_CHANNEL is not null");
            return (Criteria) this;
        }

        public Criteria andBizChannelEqualTo(String value) {
            addCriterion("BIZ_CHANNEL =", value, "bizChannel");
            return (Criteria) this;
        }

        public Criteria andBizChannelNotEqualTo(String value) {
            addCriterion("BIZ_CHANNEL <>", value, "bizChannel");
            return (Criteria) this;
        }

        public Criteria andBizChannelGreaterThan(String value) {
            addCriterion("BIZ_CHANNEL >", value, "bizChannel");
            return (Criteria) this;
        }

        public Criteria andBizChannelGreaterThanOrEqualTo(String value) {
            addCriterion("BIZ_CHANNEL >=", value, "bizChannel");
            return (Criteria) this;
        }

        public Criteria andBizChannelLessThan(String value) {
            addCriterion("BIZ_CHANNEL <", value, "bizChannel");
            return (Criteria) this;
        }

        public Criteria andBizChannelLessThanOrEqualTo(String value) {
            addCriterion("BIZ_CHANNEL <=", value, "bizChannel");
            return (Criteria) this;
        }

        public Criteria andBizChannelLike(String value) {
            addCriterion("BIZ_CHANNEL like", value, "bizChannel");
            return (Criteria) this;
        }

        public Criteria andBizChannelNotLike(String value) {
            addCriterion("BIZ_CHANNEL not like", value, "bizChannel");
            return (Criteria) this;
        }

        public Criteria andBizChannelIn(List<String> values) {
            addCriterion("BIZ_CHANNEL in", values, "bizChannel");
            return (Criteria) this;
        }

        public Criteria andBizChannelNotIn(List<String> values) {
            addCriterion("BIZ_CHANNEL not in", values, "bizChannel");
            return (Criteria) this;
        }

        public Criteria andBizChannelBetween(String value1, String value2) {
            addCriterion("BIZ_CHANNEL between", value1, value2, "bizChannel");
            return (Criteria) this;
        }

        public Criteria andBizChannelNotBetween(String value1, String value2) {
            addCriterion("BIZ_CHANNEL not between", value1, value2, "bizChannel");
            return (Criteria) this;
        }

        public Criteria andBizAgencyIsNull() {
            addCriterion("BIZ_AGENCY is null");
            return (Criteria) this;
        }

        public Criteria andBizAgencyIsNotNull() {
            addCriterion("BIZ_AGENCY is not null");
            return (Criteria) this;
        }

        public Criteria andBizAgencyEqualTo(String value) {
            addCriterion("BIZ_AGENCY =", value, "bizAgency");
            return (Criteria) this;
        }

        public Criteria andBizAgencyNotEqualTo(String value) {
            addCriterion("BIZ_AGENCY <>", value, "bizAgency");
            return (Criteria) this;
        }

        public Criteria andBizAgencyGreaterThan(String value) {
            addCriterion("BIZ_AGENCY >", value, "bizAgency");
            return (Criteria) this;
        }

        public Criteria andBizAgencyGreaterThanOrEqualTo(String value) {
            addCriterion("BIZ_AGENCY >=", value, "bizAgency");
            return (Criteria) this;
        }

        public Criteria andBizAgencyLessThan(String value) {
            addCriterion("BIZ_AGENCY <", value, "bizAgency");
            return (Criteria) this;
        }

        public Criteria andBizAgencyLessThanOrEqualTo(String value) {
            addCriterion("BIZ_AGENCY <=", value, "bizAgency");
            return (Criteria) this;
        }

        public Criteria andBizAgencyLike(String value) {
            addCriterion("BIZ_AGENCY like", value, "bizAgency");
            return (Criteria) this;
        }

        public Criteria andBizAgencyNotLike(String value) {
            addCriterion("BIZ_AGENCY not like", value, "bizAgency");
            return (Criteria) this;
        }

        public Criteria andBizAgencyIn(List<String> values) {
            addCriterion("BIZ_AGENCY in", values, "bizAgency");
            return (Criteria) this;
        }

        public Criteria andBizAgencyNotIn(List<String> values) {
            addCriterion("BIZ_AGENCY not in", values, "bizAgency");
            return (Criteria) this;
        }

        public Criteria andBizAgencyBetween(String value1, String value2) {
            addCriterion("BIZ_AGENCY between", value1, value2, "bizAgency");
            return (Criteria) this;
        }

        public Criteria andBizAgencyNotBetween(String value1, String value2) {
            addCriterion("BIZ_AGENCY not between", value1, value2, "bizAgency");
            return (Criteria) this;
        }

        public Criteria andSignTypeIsNull() {
            addCriterion("SIGN_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSignTypeIsNotNull() {
            addCriterion("SIGN_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSignTypeEqualTo(String value) {
            addCriterion("SIGN_TYPE =", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeNotEqualTo(String value) {
            addCriterion("SIGN_TYPE <>", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeGreaterThan(String value) {
            addCriterion("SIGN_TYPE >", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SIGN_TYPE >=", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeLessThan(String value) {
            addCriterion("SIGN_TYPE <", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeLessThanOrEqualTo(String value) {
            addCriterion("SIGN_TYPE <=", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeLike(String value) {
            addCriterion("SIGN_TYPE like", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeNotLike(String value) {
            addCriterion("SIGN_TYPE not like", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeIn(List<String> values) {
            addCriterion("SIGN_TYPE in", values, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeNotIn(List<String> values) {
            addCriterion("SIGN_TYPE not in", values, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeBetween(String value1, String value2) {
            addCriterion("SIGN_TYPE between", value1, value2, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeNotBetween(String value1, String value2) {
            addCriterion("SIGN_TYPE not between", value1, value2, "signType");
            return (Criteria) this;
        }

        public Criteria andSignIsNull() {
            addCriterion("SIGN is null");
            return (Criteria) this;
        }

        public Criteria andSignIsNotNull() {
            addCriterion("SIGN is not null");
            return (Criteria) this;
        }

        public Criteria andSignEqualTo(String value) {
            addCriterion("SIGN =", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotEqualTo(String value) {
            addCriterion("SIGN <>", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignGreaterThan(String value) {
            addCriterion("SIGN >", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignGreaterThanOrEqualTo(String value) {
            addCriterion("SIGN >=", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLessThan(String value) {
            addCriterion("SIGN <", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLessThanOrEqualTo(String value) {
            addCriterion("SIGN <=", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLike(String value) {
            addCriterion("SIGN like", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotLike(String value) {
            addCriterion("SIGN not like", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignIn(List<String> values) {
            addCriterion("SIGN in", values, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotIn(List<String> values) {
            addCriterion("SIGN not in", values, "sign");
            return (Criteria) this;
        }

        public Criteria andSignBetween(String value1, String value2) {
            addCriterion("SIGN between", value1, value2, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotBetween(String value1, String value2) {
            addCriterion("SIGN not between", value1, value2, "sign");
            return (Criteria) this;
        }

        public Criteria andSignFormatIsNull() {
            addCriterion("SIGN_FORMAT is null");
            return (Criteria) this;
        }

        public Criteria andSignFormatIsNotNull() {
            addCriterion("SIGN_FORMAT is not null");
            return (Criteria) this;
        }

        public Criteria andSignFormatEqualTo(String value) {
            addCriterion("SIGN_FORMAT =", value, "signFormat");
            return (Criteria) this;
        }

        public Criteria andSignFormatNotEqualTo(String value) {
            addCriterion("SIGN_FORMAT <>", value, "signFormat");
            return (Criteria) this;
        }

        public Criteria andSignFormatGreaterThan(String value) {
            addCriterion("SIGN_FORMAT >", value, "signFormat");
            return (Criteria) this;
        }

        public Criteria andSignFormatGreaterThanOrEqualTo(String value) {
            addCriterion("SIGN_FORMAT >=", value, "signFormat");
            return (Criteria) this;
        }

        public Criteria andSignFormatLessThan(String value) {
            addCriterion("SIGN_FORMAT <", value, "signFormat");
            return (Criteria) this;
        }

        public Criteria andSignFormatLessThanOrEqualTo(String value) {
            addCriterion("SIGN_FORMAT <=", value, "signFormat");
            return (Criteria) this;
        }

        public Criteria andSignFormatLike(String value) {
            addCriterion("SIGN_FORMAT like", value, "signFormat");
            return (Criteria) this;
        }

        public Criteria andSignFormatNotLike(String value) {
            addCriterion("SIGN_FORMAT not like", value, "signFormat");
            return (Criteria) this;
        }

        public Criteria andSignFormatIn(List<String> values) {
            addCriterion("SIGN_FORMAT in", values, "signFormat");
            return (Criteria) this;
        }

        public Criteria andSignFormatNotIn(List<String> values) {
            addCriterion("SIGN_FORMAT not in", values, "signFormat");
            return (Criteria) this;
        }

        public Criteria andSignFormatBetween(String value1, String value2) {
            addCriterion("SIGN_FORMAT between", value1, value2, "signFormat");
            return (Criteria) this;
        }

        public Criteria andSignFormatNotBetween(String value1, String value2) {
            addCriterion("SIGN_FORMAT not between", value1, value2, "signFormat");
            return (Criteria) this;
        }

        public Criteria andCharsetIsNull() {
            addCriterion("CHARSET is null");
            return (Criteria) this;
        }

        public Criteria andCharsetIsNotNull() {
            addCriterion("CHARSET is not null");
            return (Criteria) this;
        }

        public Criteria andCharsetEqualTo(String value) {
            addCriterion("CHARSET =", value, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetNotEqualTo(String value) {
            addCriterion("CHARSET <>", value, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetGreaterThan(String value) {
            addCriterion("CHARSET >", value, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetGreaterThanOrEqualTo(String value) {
            addCriterion("CHARSET >=", value, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetLessThan(String value) {
            addCriterion("CHARSET <", value, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetLessThanOrEqualTo(String value) {
            addCriterion("CHARSET <=", value, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetLike(String value) {
            addCriterion("CHARSET like", value, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetNotLike(String value) {
            addCriterion("CHARSET not like", value, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetIn(List<String> values) {
            addCriterion("CHARSET in", values, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetNotIn(List<String> values) {
            addCriterion("CHARSET not in", values, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetBetween(String value1, String value2) {
            addCriterion("CHARSET between", value1, value2, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetNotBetween(String value1, String value2) {
            addCriterion("CHARSET not between", value1, value2, "charset");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("VERSION like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("VERSION not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andAppInfoIsNull() {
            addCriterion("APP_INFO is null");
            return (Criteria) this;
        }

        public Criteria andAppInfoIsNotNull() {
            addCriterion("APP_INFO is not null");
            return (Criteria) this;
        }

        public Criteria andAppInfoEqualTo(String value) {
            addCriterion("APP_INFO =", value, "appInfo");
            return (Criteria) this;
        }

        public Criteria andAppInfoNotEqualTo(String value) {
            addCriterion("APP_INFO <>", value, "appInfo");
            return (Criteria) this;
        }

        public Criteria andAppInfoGreaterThan(String value) {
            addCriterion("APP_INFO >", value, "appInfo");
            return (Criteria) this;
        }

        public Criteria andAppInfoGreaterThanOrEqualTo(String value) {
            addCriterion("APP_INFO >=", value, "appInfo");
            return (Criteria) this;
        }

        public Criteria andAppInfoLessThan(String value) {
            addCriterion("APP_INFO <", value, "appInfo");
            return (Criteria) this;
        }

        public Criteria andAppInfoLessThanOrEqualTo(String value) {
            addCriterion("APP_INFO <=", value, "appInfo");
            return (Criteria) this;
        }

        public Criteria andAppInfoLike(String value) {
            addCriterion("APP_INFO like", value, "appInfo");
            return (Criteria) this;
        }

        public Criteria andAppInfoNotLike(String value) {
            addCriterion("APP_INFO not like", value, "appInfo");
            return (Criteria) this;
        }

        public Criteria andAppInfoIn(List<String> values) {
            addCriterion("APP_INFO in", values, "appInfo");
            return (Criteria) this;
        }

        public Criteria andAppInfoNotIn(List<String> values) {
            addCriterion("APP_INFO not in", values, "appInfo");
            return (Criteria) this;
        }

        public Criteria andAppInfoBetween(String value1, String value2) {
            addCriterion("APP_INFO between", value1, value2, "appInfo");
            return (Criteria) this;
        }

        public Criteria andAppInfoNotBetween(String value1, String value2) {
            addCriterion("APP_INFO not between", value1, value2, "appInfo");
            return (Criteria) this;
        }

        public Criteria andMachineIsNull() {
            addCriterion("MACHINE is null");
            return (Criteria) this;
        }

        public Criteria andMachineIsNotNull() {
            addCriterion("MACHINE is not null");
            return (Criteria) this;
        }

        public Criteria andMachineEqualTo(String value) {
            addCriterion("MACHINE =", value, "machine");
            return (Criteria) this;
        }

        public Criteria andMachineNotEqualTo(String value) {
            addCriterion("MACHINE <>", value, "machine");
            return (Criteria) this;
        }

        public Criteria andMachineGreaterThan(String value) {
            addCriterion("MACHINE >", value, "machine");
            return (Criteria) this;
        }

        public Criteria andMachineGreaterThanOrEqualTo(String value) {
            addCriterion("MACHINE >=", value, "machine");
            return (Criteria) this;
        }

        public Criteria andMachineLessThan(String value) {
            addCriterion("MACHINE <", value, "machine");
            return (Criteria) this;
        }

        public Criteria andMachineLessThanOrEqualTo(String value) {
            addCriterion("MACHINE <=", value, "machine");
            return (Criteria) this;
        }

        public Criteria andMachineLike(String value) {
            addCriterion("MACHINE like", value, "machine");
            return (Criteria) this;
        }

        public Criteria andMachineNotLike(String value) {
            addCriterion("MACHINE not like", value, "machine");
            return (Criteria) this;
        }

        public Criteria andMachineIn(List<String> values) {
            addCriterion("MACHINE in", values, "machine");
            return (Criteria) this;
        }

        public Criteria andMachineNotIn(List<String> values) {
            addCriterion("MACHINE not in", values, "machine");
            return (Criteria) this;
        }

        public Criteria andMachineBetween(String value1, String value2) {
            addCriterion("MACHINE between", value1, value2, "machine");
            return (Criteria) this;
        }

        public Criteria andMachineNotBetween(String value1, String value2) {
            addCriterion("MACHINE not between", value1, value2, "machine");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("DEVICE_ID is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("DEVICE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(String value) {
            addCriterion("DEVICE_ID =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(String value) {
            addCriterion("DEVICE_ID <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(String value) {
            addCriterion("DEVICE_ID >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(String value) {
            addCriterion("DEVICE_ID >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(String value) {
            addCriterion("DEVICE_ID <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(String value) {
            addCriterion("DEVICE_ID <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLike(String value) {
            addCriterion("DEVICE_ID like", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotLike(String value) {
            addCriterion("DEVICE_ID not like", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<String> values) {
            addCriterion("DEVICE_ID in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<String> values) {
            addCriterion("DEVICE_ID not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(String value1, String value2) {
            addCriterion("DEVICE_ID between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(String value1, String value2) {
            addCriterion("DEVICE_ID not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andCreateIpIsNull() {
            addCriterion("CREATE_IP is null");
            return (Criteria) this;
        }

        public Criteria andCreateIpIsNotNull() {
            addCriterion("CREATE_IP is not null");
            return (Criteria) this;
        }

        public Criteria andCreateIpEqualTo(String value) {
            addCriterion("CREATE_IP =", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpNotEqualTo(String value) {
            addCriterion("CREATE_IP <>", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpGreaterThan(String value) {
            addCriterion("CREATE_IP >", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_IP >=", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpLessThan(String value) {
            addCriterion("CREATE_IP <", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpLessThanOrEqualTo(String value) {
            addCriterion("CREATE_IP <=", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpLike(String value) {
            addCriterion("CREATE_IP like", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpNotLike(String value) {
            addCriterion("CREATE_IP not like", value, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpIn(List<String> values) {
            addCriterion("CREATE_IP in", values, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpNotIn(List<String> values) {
            addCriterion("CREATE_IP not in", values, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpBetween(String value1, String value2) {
            addCriterion("CREATE_IP between", value1, value2, "createIp");
            return (Criteria) this;
        }

        public Criteria andCreateIpNotBetween(String value1, String value2) {
            addCriterion("CREATE_IP not between", value1, value2, "createIp");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlIsNull() {
            addCriterion("NOTIFY_URL is null");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlIsNotNull() {
            addCriterion("NOTIFY_URL is not null");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlEqualTo(String value) {
            addCriterion("NOTIFY_URL =", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlNotEqualTo(String value) {
            addCriterion("NOTIFY_URL <>", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlGreaterThan(String value) {
            addCriterion("NOTIFY_URL >", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlGreaterThanOrEqualTo(String value) {
            addCriterion("NOTIFY_URL >=", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlLessThan(String value) {
            addCriterion("NOTIFY_URL <", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlLessThanOrEqualTo(String value) {
            addCriterion("NOTIFY_URL <=", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlLike(String value) {
            addCriterion("NOTIFY_URL like", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlNotLike(String value) {
            addCriterion("NOTIFY_URL not like", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlIn(List<String> values) {
            addCriterion("NOTIFY_URL in", values, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlNotIn(List<String> values) {
            addCriterion("NOTIFY_URL not in", values, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlBetween(String value1, String value2) {
            addCriterion("NOTIFY_URL between", value1, value2, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlNotBetween(String value1, String value2) {
            addCriterion("NOTIFY_URL not between", value1, value2, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andRequestTimeIsNull() {
            addCriterion("REQUEST_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRequestTimeIsNotNull() {
            addCriterion("REQUEST_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRequestTimeEqualTo(String value) {
            addCriterion("REQUEST_TIME =", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeNotEqualTo(String value) {
            addCriterion("REQUEST_TIME <>", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeGreaterThan(String value) {
            addCriterion("REQUEST_TIME >", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeGreaterThanOrEqualTo(String value) {
            addCriterion("REQUEST_TIME >=", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeLessThan(String value) {
            addCriterion("REQUEST_TIME <", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeLessThanOrEqualTo(String value) {
            addCriterion("REQUEST_TIME <=", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeLike(String value) {
            addCriterion("REQUEST_TIME like", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeNotLike(String value) {
            addCriterion("REQUEST_TIME not like", value, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeIn(List<String> values) {
            addCriterion("REQUEST_TIME in", values, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeNotIn(List<String> values) {
            addCriterion("REQUEST_TIME not in", values, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeBetween(String value1, String value2) {
            addCriterion("REQUEST_TIME between", value1, value2, "requestTime");
            return (Criteria) this;
        }

        public Criteria andRequestTimeNotBetween(String value1, String value2) {
            addCriterion("REQUEST_TIME not between", value1, value2, "requestTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andRetTimeIsNull() {
            addCriterion("RET_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRetTimeIsNotNull() {
            addCriterion("RET_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRetTimeEqualTo(String value) {
            addCriterion("RET_TIME =", value, "retTime");
            return (Criteria) this;
        }

        public Criteria andRetTimeNotEqualTo(String value) {
            addCriterion("RET_TIME <>", value, "retTime");
            return (Criteria) this;
        }

        public Criteria andRetTimeGreaterThan(String value) {
            addCriterion("RET_TIME >", value, "retTime");
            return (Criteria) this;
        }

        public Criteria andRetTimeGreaterThanOrEqualTo(String value) {
            addCriterion("RET_TIME >=", value, "retTime");
            return (Criteria) this;
        }

        public Criteria andRetTimeLessThan(String value) {
            addCriterion("RET_TIME <", value, "retTime");
            return (Criteria) this;
        }

        public Criteria andRetTimeLessThanOrEqualTo(String value) {
            addCriterion("RET_TIME <=", value, "retTime");
            return (Criteria) this;
        }

        public Criteria andRetTimeLike(String value) {
            addCriterion("RET_TIME like", value, "retTime");
            return (Criteria) this;
        }

        public Criteria andRetTimeNotLike(String value) {
            addCriterion("RET_TIME not like", value, "retTime");
            return (Criteria) this;
        }

        public Criteria andRetTimeIn(List<String> values) {
            addCriterion("RET_TIME in", values, "retTime");
            return (Criteria) this;
        }

        public Criteria andRetTimeNotIn(List<String> values) {
            addCriterion("RET_TIME not in", values, "retTime");
            return (Criteria) this;
        }

        public Criteria andRetTimeBetween(String value1, String value2) {
            addCriterion("RET_TIME between", value1, value2, "retTime");
            return (Criteria) this;
        }

        public Criteria andRetTimeNotBetween(String value1, String value2) {
            addCriterion("RET_TIME not between", value1, value2, "retTime");
            return (Criteria) this;
        }

        public Criteria andSubCodeIsNull() {
            addCriterion("SUB_CODE is null");
            return (Criteria) this;
        }

        public Criteria andSubCodeIsNotNull() {
            addCriterion("SUB_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andSubCodeEqualTo(String value) {
            addCriterion("SUB_CODE =", value, "subCode");
            return (Criteria) this;
        }

        public Criteria andSubCodeNotEqualTo(String value) {
            addCriterion("SUB_CODE <>", value, "subCode");
            return (Criteria) this;
        }

        public Criteria andSubCodeGreaterThan(String value) {
            addCriterion("SUB_CODE >", value, "subCode");
            return (Criteria) this;
        }

        public Criteria andSubCodeGreaterThanOrEqualTo(String value) {
            addCriterion("SUB_CODE >=", value, "subCode");
            return (Criteria) this;
        }

        public Criteria andSubCodeLessThan(String value) {
            addCriterion("SUB_CODE <", value, "subCode");
            return (Criteria) this;
        }

        public Criteria andSubCodeLessThanOrEqualTo(String value) {
            addCriterion("SUB_CODE <=", value, "subCode");
            return (Criteria) this;
        }

        public Criteria andSubCodeLike(String value) {
            addCriterion("SUB_CODE like", value, "subCode");
            return (Criteria) this;
        }

        public Criteria andSubCodeNotLike(String value) {
            addCriterion("SUB_CODE not like", value, "subCode");
            return (Criteria) this;
        }

        public Criteria andSubCodeIn(List<String> values) {
            addCriterion("SUB_CODE in", values, "subCode");
            return (Criteria) this;
        }

        public Criteria andSubCodeNotIn(List<String> values) {
            addCriterion("SUB_CODE not in", values, "subCode");
            return (Criteria) this;
        }

        public Criteria andSubCodeBetween(String value1, String value2) {
            addCriterion("SUB_CODE between", value1, value2, "subCode");
            return (Criteria) this;
        }

        public Criteria andSubCodeNotBetween(String value1, String value2) {
            addCriterion("SUB_CODE not between", value1, value2, "subCode");
            return (Criteria) this;
        }

        public Criteria andSubMessageIsNull() {
            addCriterion("SUB_MESSAGE is null");
            return (Criteria) this;
        }

        public Criteria andSubMessageIsNotNull() {
            addCriterion("SUB_MESSAGE is not null");
            return (Criteria) this;
        }

        public Criteria andSubMessageEqualTo(String value) {
            addCriterion("SUB_MESSAGE =", value, "subMessage");
            return (Criteria) this;
        }

        public Criteria andSubMessageNotEqualTo(String value) {
            addCriterion("SUB_MESSAGE <>", value, "subMessage");
            return (Criteria) this;
        }

        public Criteria andSubMessageGreaterThan(String value) {
            addCriterion("SUB_MESSAGE >", value, "subMessage");
            return (Criteria) this;
        }

        public Criteria andSubMessageGreaterThanOrEqualTo(String value) {
            addCriterion("SUB_MESSAGE >=", value, "subMessage");
            return (Criteria) this;
        }

        public Criteria andSubMessageLessThan(String value) {
            addCriterion("SUB_MESSAGE <", value, "subMessage");
            return (Criteria) this;
        }

        public Criteria andSubMessageLessThanOrEqualTo(String value) {
            addCriterion("SUB_MESSAGE <=", value, "subMessage");
            return (Criteria) this;
        }

        public Criteria andSubMessageLike(String value) {
            addCriterion("SUB_MESSAGE like", value, "subMessage");
            return (Criteria) this;
        }

        public Criteria andSubMessageNotLike(String value) {
            addCriterion("SUB_MESSAGE not like", value, "subMessage");
            return (Criteria) this;
        }

        public Criteria andSubMessageIn(List<String> values) {
            addCriterion("SUB_MESSAGE in", values, "subMessage");
            return (Criteria) this;
        }

        public Criteria andSubMessageNotIn(List<String> values) {
            addCriterion("SUB_MESSAGE not in", values, "subMessage");
            return (Criteria) this;
        }

        public Criteria andSubMessageBetween(String value1, String value2) {
            addCriterion("SUB_MESSAGE between", value1, value2, "subMessage");
            return (Criteria) this;
        }

        public Criteria andSubMessageNotBetween(String value1, String value2) {
            addCriterion("SUB_MESSAGE not between", value1, value2, "subMessage");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("CODE in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("CODE not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andMessageIsNull() {
            addCriterion("MESSAGE is null");
            return (Criteria) this;
        }

        public Criteria andMessageIsNotNull() {
            addCriterion("MESSAGE is not null");
            return (Criteria) this;
        }

        public Criteria andMessageEqualTo(String value) {
            addCriterion("MESSAGE =", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotEqualTo(String value) {
            addCriterion("MESSAGE <>", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageGreaterThan(String value) {
            addCriterion("MESSAGE >", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageGreaterThanOrEqualTo(String value) {
            addCriterion("MESSAGE >=", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLessThan(String value) {
            addCriterion("MESSAGE <", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLessThanOrEqualTo(String value) {
            addCriterion("MESSAGE <=", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLike(String value) {
            addCriterion("MESSAGE like", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotLike(String value) {
            addCriterion("MESSAGE not like", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageIn(List<String> values) {
            addCriterion("MESSAGE in", values, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotIn(List<String> values) {
            addCriterion("MESSAGE not in", values, "message");
            return (Criteria) this;
        }

        public Criteria andMessageBetween(String value1, String value2) {
            addCriterion("MESSAGE between", value1, value2, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotBetween(String value1, String value2) {
            addCriterion("MESSAGE not between", value1, value2, "message");
            return (Criteria) this;
        }

        public Criteria andReserveIsNull() {
            addCriterion("RESERVE is null");
            return (Criteria) this;
        }

        public Criteria andReserveIsNotNull() {
            addCriterion("RESERVE is not null");
            return (Criteria) this;
        }

        public Criteria andReserveEqualTo(String value) {
            addCriterion("RESERVE =", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveNotEqualTo(String value) {
            addCriterion("RESERVE <>", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveGreaterThan(String value) {
            addCriterion("RESERVE >", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveGreaterThanOrEqualTo(String value) {
            addCriterion("RESERVE >=", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveLessThan(String value) {
            addCriterion("RESERVE <", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveLessThanOrEqualTo(String value) {
            addCriterion("RESERVE <=", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveLike(String value) {
            addCriterion("RESERVE like", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveNotLike(String value) {
            addCriterion("RESERVE not like", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveIn(List<String> values) {
            addCriterion("RESERVE in", values, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveNotIn(List<String> values) {
            addCriterion("RESERVE not in", values, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveBetween(String value1, String value2) {
            addCriterion("RESERVE between", value1, value2, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveNotBetween(String value1, String value2) {
            addCriterion("RESERVE not between", value1, value2, "reserve");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table umsmember..t_translog
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table umsmember..t_translog
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}