package com.ums.mbr.service.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class Card implements Serializable {
    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 系统跟踪流水
     * This field corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    private String retserial;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 用户卡号
     * This field corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    private String cardNo;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 剩余金额
     * This field corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    private BigDecimal remainCash;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 所属渠道方，取值为T_MALL的NAME
     * This field corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    private String mallName;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 客户类型
     * This field corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    private String customerType;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 卡名称
     * This field corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    private String cardName;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 用户ID
     * This field corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    private String customerId;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 折扣。0到1的小数
     * This field corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    private BigDecimal discount;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 手机号
     * This field corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 用户性别
     * This field corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    private String gender;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 用户生日
     * This field corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 用户名称
     * This field corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 创建时间
     * This field corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 更新时间
     * This field corresponds to the database table umsmember..t_card
     *
     * @mbg.generated
     */
    private String refreshTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_card.RETSERIAL
     *
     * @return the value of umsmember..t_card.RETSERIAL
     *
     * @mbg.generated
     */
    public String getRetserial() {
        return retserial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_card.RETSERIAL
     *
     * @param retserial the value for umsmember..t_card.RETSERIAL
     *
     * @mbg.generated
     */
    public void setRetserial(String retserial) {
        this.retserial = retserial == null ? null : retserial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_card.CARD_NO
     *
     * @return the value of umsmember..t_card.CARD_NO
     *
     * @mbg.generated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_card.CARD_NO
     *
     * @param cardNo the value for umsmember..t_card.CARD_NO
     *
     * @mbg.generated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_card.REMAIN_CASH
     *
     * @return the value of umsmember..t_card.REMAIN_CASH
     *
     * @mbg.generated
     */
    public BigDecimal getRemainCash() {
        return remainCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_card.REMAIN_CASH
     *
     * @param remainCash the value for umsmember..t_card.REMAIN_CASH
     *
     * @mbg.generated
     */
    public void setRemainCash(BigDecimal remainCash) {
        this.remainCash = remainCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_card.MALL_NAME
     *
     * @return the value of umsmember..t_card.MALL_NAME
     *
     * @mbg.generated
     */
    public String getMallName() {
        return mallName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_card.MALL_NAME
     *
     * @param mallName the value for umsmember..t_card.MALL_NAME
     *
     * @mbg.generated
     */
    public void setMallName(String mallName) {
        this.mallName = mallName == null ? null : mallName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_card.CUSTOMER_TYPE
     *
     * @return the value of umsmember..t_card.CUSTOMER_TYPE
     *
     * @mbg.generated
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_card.CUSTOMER_TYPE
     *
     * @param customerType the value for umsmember..t_card.CUSTOMER_TYPE
     *
     * @mbg.generated
     */
    public void setCustomerType(String customerType) {
        this.customerType = customerType == null ? null : customerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_card.CARD_NAME
     *
     * @return the value of umsmember..t_card.CARD_NAME
     *
     * @mbg.generated
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_card.CARD_NAME
     *
     * @param cardName the value for umsmember..t_card.CARD_NAME
     *
     * @mbg.generated
     */
    public void setCardName(String cardName) {
        this.cardName = cardName == null ? null : cardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_card.CUSTOMER_ID
     *
     * @return the value of umsmember..t_card.CUSTOMER_ID
     *
     * @mbg.generated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_card.CUSTOMER_ID
     *
     * @param customerId the value for umsmember..t_card.CUSTOMER_ID
     *
     * @mbg.generated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_card.DISCOUNT
     *
     * @return the value of umsmember..t_card.DISCOUNT
     *
     * @mbg.generated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_card.DISCOUNT
     *
     * @param discount the value for umsmember..t_card.DISCOUNT
     *
     * @mbg.generated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_card.TELEPHONE
     *
     * @return the value of umsmember..t_card.TELEPHONE
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_card.TELEPHONE
     *
     * @param telephone the value for umsmember..t_card.TELEPHONE
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_card.GENDER
     *
     * @return the value of umsmember..t_card.GENDER
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_card.GENDER
     *
     * @param gender the value for umsmember..t_card.GENDER
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_card.BIRTHDAY
     *
     * @return the value of umsmember..t_card.BIRTHDAY
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_card.BIRTHDAY
     *
     * @param birthday the value for umsmember..t_card.BIRTHDAY
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_card.CUSTOMER_NAME
     *
     * @return the value of umsmember..t_card.CUSTOMER_NAME
     *
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_card.CUSTOMER_NAME
     *
     * @param customerName the value for umsmember..t_card.CUSTOMER_NAME
     *
     * @mbg.generated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_card.CREATE_TIME
     *
     * @return the value of umsmember..t_card.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_card.CREATE_TIME
     *
     * @param createTime the value for umsmember..t_card.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_card.REFRESH_TIME
     *
     * @return the value of umsmember..t_card.REFRESH_TIME
     *
     * @mbg.generated
     */
    public String getRefreshTime() {
        return refreshTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_card.REFRESH_TIME
     *
     * @param refreshTime the value for umsmember..t_card.REFRESH_TIME
     *
     * @mbg.generated
     */
    public void setRefreshTime(String refreshTime) {
        this.refreshTime = refreshTime == null ? null : refreshTime.trim();
    }
}