package com.ums.mbr.service.domain;

import java.io.Serializable;

public class CouponKey implements Serializable {
    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 系统跟踪流水
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private String retserial;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 会员系统的券码标识号
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private String coupserial;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.RETSERIAL
     *
     * @return the value of umsmember..t_coupon.RETSERIAL
     *
     * @mbg.generated
     */
    public String getRetserial() {
        return retserial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.RETSERIAL
     *
     * @param retserial the value for umsmember..t_coupon.RETSERIAL
     *
     * @mbg.generated
     */
    public void setRetserial(String retserial) {
        this.retserial = retserial == null ? null : retserial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.COUPSERIAL
     *
     * @return the value of umsmember..t_coupon.COUPSERIAL
     *
     * @mbg.generated
     */
    public String getCoupserial() {
        return coupserial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.COUPSERIAL
     *
     * @param coupserial the value for umsmember..t_coupon.COUPSERIAL
     *
     * @mbg.generated
     */
    public void setCoupserial(String coupserial) {
        this.coupserial = coupserial == null ? null : coupserial.trim();
    }
}