package com.ums.mbr.service.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class Coupon implements Serializable {
    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 系统跟踪流水
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private String retserial;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 客户类型
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private String customerType;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 客户号
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private String customerId;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 支付代码
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private String payCode;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 核销券码号
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private String couponNo;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 优惠券面值(或减免值)
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private BigDecimal couponValue;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 可用券数量
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private Integer couponNum;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 优惠券名称
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private String couponName;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 有效期开始时间
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private String statrtTime;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 有效期结束时间
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private String endTime;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 起用金额
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private BigDecimal serviceAmount;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 生成门店名称
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private String createShop = "";

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 优惠券状态
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private String verifyState;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 是否有门店限制
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private String isLimitedShop;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 使用门店名称
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private String limmitedShop;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 使用说明
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private String couponDesc;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 优惠券图片路径
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private String couponImage;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 创建时间
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 更新时间
     * This field corresponds to the database table umsmember..t_coupon
     *
     * @mbg.generated
     */
    private String refreshTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.RETSERIAL
     *
     * @return the value of umsmember..t_coupon.RETSERIAL
     *
     * @mbg.generated
     */
    public String getRetserial() {
        return retserial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.RETSERIAL
     *
     * @param retserial the value for umsmember..t_coupon.RETSERIAL
     *
     * @mbg.generated
     */
    public void setRetserial(String retserial) {
        this.retserial = retserial == null ? null : retserial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.CUSTOMER_TYPE
     *
     * @return the value of umsmember..t_coupon.CUSTOMER_TYPE
     *
     * @mbg.generated
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.CUSTOMER_TYPE
     *
     * @param customerType the value for umsmember..t_coupon.CUSTOMER_TYPE
     *
     * @mbg.generated
     */
    public void setCustomerType(String customerType) {
        this.customerType = customerType == null ? null : customerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.CUSTOMER_ID
     *
     * @return the value of umsmember..t_coupon.CUSTOMER_ID
     *
     * @mbg.generated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.CUSTOMER_ID
     *
     * @param customerId the value for umsmember..t_coupon.CUSTOMER_ID
     *
     * @mbg.generated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.PAY_CODE
     *
     * @return the value of umsmember..t_coupon.PAY_CODE
     *
     * @mbg.generated
     */
    public String getPayCode() {
        return payCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.PAY_CODE
     *
     * @param payCode the value for umsmember..t_coupon.PAY_CODE
     *
     * @mbg.generated
     */
    public void setPayCode(String payCode) {
        this.payCode = payCode == null ? null : payCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.COUPON_NO
     *
     * @return the value of umsmember..t_coupon.COUPON_NO
     *
     * @mbg.generated
     */
    public String getCouponNo() {
        return couponNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.COUPON_NO
     *
     * @param couponNo the value for umsmember..t_coupon.COUPON_NO
     *
     * @mbg.generated
     */
    public void setCouponNo(String couponNo) {
        this.couponNo = couponNo == null ? null : couponNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.COUPON_VALUE
     *
     * @return the value of umsmember..t_coupon.COUPON_VALUE
     *
     * @mbg.generated
     */
    public BigDecimal getCouponValue() {
        return couponValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.COUPON_VALUE
     *
     * @param couponValue the value for umsmember..t_coupon.COUPON_VALUE
     *
     * @mbg.generated
     */
    public void setCouponValue(BigDecimal couponValue) {
        this.couponValue = couponValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.COUPON_NUM
     *
     * @return the value of umsmember..t_coupon.COUPON_NUM
     *
     * @mbg.generated
     */
    public Integer getCouponNum() {
        return couponNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.COUPON_NUM
     *
     * @param couponNum the value for umsmember..t_coupon.COUPON_NUM
     *
     * @mbg.generated
     */
    public void setCouponNum(Integer couponNum) {
        this.couponNum = couponNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.COUPON_NAME
     *
     * @return the value of umsmember..t_coupon.COUPON_NAME
     *
     * @mbg.generated
     */
    public String getCouponName() {
        return couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.COUPON_NAME
     *
     * @param couponName the value for umsmember..t_coupon.COUPON_NAME
     *
     * @mbg.generated
     */
    public void setCouponName(String couponName) {
        this.couponName = couponName == null ? null : couponName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.STATRT_TIME
     *
     * @return the value of umsmember..t_coupon.STATRT_TIME
     *
     * @mbg.generated
     */
    public String getStatrtTime() {
        return statrtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.STATRT_TIME
     *
     * @param statrtTime the value for umsmember..t_coupon.STATRT_TIME
     *
     * @mbg.generated
     */
    public void setStatrtTime(String statrtTime) {
        this.statrtTime = statrtTime == null ? null : statrtTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.END_TIME
     *
     * @return the value of umsmember..t_coupon.END_TIME
     *
     * @mbg.generated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.END_TIME
     *
     * @param endTime the value for umsmember..t_coupon.END_TIME
     *
     * @mbg.generated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.SERVICE_AMOUNT
     *
     * @return the value of umsmember..t_coupon.SERVICE_AMOUNT
     *
     * @mbg.generated
     */
    public BigDecimal getServiceAmount() {
        return serviceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.SERVICE_AMOUNT
     *
     * @param serviceAmount the value for umsmember..t_coupon.SERVICE_AMOUNT
     *
     * @mbg.generated
     */
    public void setServiceAmount(BigDecimal serviceAmount) {
        this.serviceAmount = serviceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.CREATE_SHOP
     *
     * @return the value of umsmember..t_coupon.CREATE_SHOP
     *
     * @mbg.generated
     */
    public String getCreateShop() {
        return createShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.CREATE_SHOP
     *
     * @param createShop the value for umsmember..t_coupon.CREATE_SHOP
     *
     * @mbg.generated
     */
    public void setCreateShop(String createShop) {
        this.createShop = createShop == null ? null : createShop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.VERIFY_STATE
     *
     * @return the value of umsmember..t_coupon.VERIFY_STATE
     *
     * @mbg.generated
     */
    public String getVerifyState() {
        return verifyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.VERIFY_STATE
     *
     * @param verifyState the value for umsmember..t_coupon.VERIFY_STATE
     *
     * @mbg.generated
     */
    public void setVerifyState(String verifyState) {
        this.verifyState = verifyState == null ? null : verifyState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.IS_LIMITED_SHOP
     *
     * @return the value of umsmember..t_coupon.IS_LIMITED_SHOP
     *
     * @mbg.generated
     */
    public String getIsLimitedShop() {
        return isLimitedShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.IS_LIMITED_SHOP
     *
     * @param isLimitedShop the value for umsmember..t_coupon.IS_LIMITED_SHOP
     *
     * @mbg.generated
     */
    public void setIsLimitedShop(String isLimitedShop) {
        this.isLimitedShop = isLimitedShop == null ? null : isLimitedShop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.LIMMITED_SHOP
     *
     * @return the value of umsmember..t_coupon.LIMMITED_SHOP
     *
     * @mbg.generated
     */
    public String getLimmitedShop() {
        return limmitedShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.LIMMITED_SHOP
     *
     * @param limmitedShop the value for umsmember..t_coupon.LIMMITED_SHOP
     *
     * @mbg.generated
     */
    public void setLimmitedShop(String limmitedShop) {
        this.limmitedShop = limmitedShop == null ? null : limmitedShop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.COUPON_DESC
     *
     * @return the value of umsmember..t_coupon.COUPON_DESC
     *
     * @mbg.generated
     */
    public String getCouponDesc() {
        return couponDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.COUPON_DESC
     *
     * @param couponDesc the value for umsmember..t_coupon.COUPON_DESC
     *
     * @mbg.generated
     */
    public void setCouponDesc(String couponDesc) {
        this.couponDesc = couponDesc == null ? null : couponDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.COUPON_IMAGE
     *
     * @return the value of umsmember..t_coupon.COUPON_IMAGE
     *
     * @mbg.generated
     */
    public String getCouponImage() {
        return couponImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.COUPON_IMAGE
     *
     * @param couponImage the value for umsmember..t_coupon.COUPON_IMAGE
     *
     * @mbg.generated
     */
    public void setCouponImage(String couponImage) {
        this.couponImage = couponImage == null ? null : couponImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.CREATE_TIME
     *
     * @return the value of umsmember..t_coupon.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.CREATE_TIME
     *
     * @param createTime the value for umsmember..t_coupon.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_coupon.REFRESH_TIME
     *
     * @return the value of umsmember..t_coupon.REFRESH_TIME
     *
     * @mbg.generated
     */
    public String getRefreshTime() {
        return refreshTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_coupon.REFRESH_TIME
     *
     * @param refreshTime the value for umsmember..t_coupon.REFRESH_TIME
     *
     * @mbg.generated
     */
    public void setRefreshTime(String refreshTime) {
        this.refreshTime = refreshTime == null ? null : refreshTime.trim();
    }
}