package com.ums.mbr.service.domain;

import java.io.Serializable;

public class HisTradeInfKey implements Serializable {
    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 系统跟踪流水
     * This field corresponds to the database table umsmember..t_histradeinf
     *
     * @mbg.generated
     */
    private String retserial;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 核销交易标识号
     * This field corresponds to the database table umsmember..t_histradeinf
     *
     * @mbg.generated
     */
    private String tradeserial;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_histradeinf.RETSERIAL
     *
     * @return the value of umsmember..t_histradeinf.RETSERIAL
     *
     * @mbg.generated
     */
    public String getRetserial() {
        return retserial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_histradeinf.RETSERIAL
     *
     * @param retserial the value for umsmember..t_histradeinf.RETSERIAL
     *
     * @mbg.generated
     */
    public void setRetserial(String retserial) {
        this.retserial = retserial == null ? null : retserial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_histradeinf.TRADESERIAL
     *
     * @return the value of umsmember..t_histradeinf.TRADESERIAL
     *
     * @mbg.generated
     */
    public String getTradeserial() {
        return tradeserial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_histradeinf.TRADESERIAL
     *
     * @param tradeserial the value for umsmember..t_histradeinf.TRADESERIAL
     *
     * @mbg.generated
     */
    public void setTradeserial(String tradeserial) {
        this.tradeserial = tradeserial == null ? null : tradeserial.trim();
    }
}