package com.ums.mbr.service.domain;

import java.io.Serializable;

public class PayCode implements Serializable {
    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 主键,支付代码的编号
     * This field corresponds to the database table t_pay_code
     *
     * @mbg.generated
     */
    private String id;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 支付代码的代码
     * This field corresponds to the database table t_pay_code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 支付代码的中文名称
     * This field corresponds to the database table t_pay_code
     *
     * @mbg.generated
     */
    private String name;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 状态
     * This field corresponds to the database table t_pay_code
     *
     * @mbg.generated
     */
    private String state;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 创建时间
     * This field corresponds to the database table t_pay_code
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 更新时间
     * This field corresponds to the database table t_pay_code
     *
     * @mbg.generated
     */
    private String refreshTime;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 说明
     * This field corresponds to the database table t_pay_code
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_code.ID
     *
     * @return the value of t_pay_code.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_code.ID
     *
     * @param id the value for t_pay_code.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_code.CODE
     *
     * @return the value of t_pay_code.CODE
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_code.CODE
     *
     * @param code the value for t_pay_code.CODE
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_code.NAME
     *
     * @return the value of t_pay_code.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_code.NAME
     *
     * @param name the value for t_pay_code.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_code.STATE
     *
     * @return the value of t_pay_code.STATE
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_code.STATE
     *
     * @param state the value for t_pay_code.STATE
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_code.CREATE_TIME
     *
     * @return the value of t_pay_code.CREATE_TIME
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_code.CREATE_TIME
     *
     * @param createTime the value for t_pay_code.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_code.REFRESH_TIME
     *
     * @return the value of t_pay_code.REFRESH_TIME
     *
     * @mbg.generated
     */
    public String getRefreshTime() {
        return refreshTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_code.REFRESH_TIME
     *
     * @param refreshTime the value for t_pay_code.REFRESH_TIME
     *
     * @mbg.generated
     */
    public void setRefreshTime(String refreshTime) {
        this.refreshTime = refreshTime == null ? null : refreshTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_code.NOTE
     *
     * @return the value of t_pay_code.NOTE
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_code.NOTE
     *
     * @param note the value for t_pay_code.NOTE
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}