package com.ums.mbr.service.domain;

import java.io.Serializable;

public class PayinfKey implements Serializable {
    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * 系统跟踪流水
     * This field corresponds to the database table umsmember..t_payinf
     *
     * @mbg.generated
     */
    private String retserial;

    /**
     * 通过MBG添加该条注释，域注释读取建表语句的Comment信息。
     * payment标识号
     * This field corresponds to the database table umsmember..t_payinf
     *
     * @mbg.generated
     */
    private String payinfserial;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_payinf.RETSERIAL
     *
     * @return the value of umsmember..t_payinf.RETSERIAL
     *
     * @mbg.generated
     */
    public String getRetserial() {
        return retserial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_payinf.RETSERIAL
     *
     * @param retserial the value for umsmember..t_payinf.RETSERIAL
     *
     * @mbg.generated
     */
    public void setRetserial(String retserial) {
        this.retserial = retserial == null ? null : retserial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column umsmember..t_payinf.PAYINFSERIAL
     *
     * @return the value of umsmember..t_payinf.PAYINFSERIAL
     *
     * @mbg.generated
     */
    public String getPayinfserial() {
        return payinfserial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column umsmember..t_payinf.PAYINFSERIAL
     *
     * @param payinfserial the value for umsmember..t_payinf.PAYINFSERIAL
     *
     * @mbg.generated
     */
    public void setPayinfserial(String payinfserial) {
        this.payinfserial = payinfserial == null ? null : payinfserial.trim();
    }
}